from __future__ import absolute_import

import json
import re
import threading
from collections import OrderedDict
from datetime import datetime
from pathlib import Path

from zh_audit.candidate_validation import (
    MAX_GENERATION_ATTEMPTS_PER_ITEM,
    build_attempt_history_entry,
    build_retry_context,
    build_review_retry_context,
    build_validation_retry_context,
    contains_locked_terms,
    exhausted_validation_message,
    has_matching_placeholders,
    is_chinese_explanation_text,
    normalize_review_result,
    retry_context_preview,
    sanitize_candidate_text,
    structured_retry_prompt,
    validate_candidate_text,
    validation_message,
)
from zh_audit.model_client import describe_retryable_model_response_error, model_response_debug_payload
from zh_audit.terminology_xlsx import exact_terminology_translation, match_locked_terms
from zh_audit.utils import contains_han, decode_unicode_escapes


SQL_TRANSLATION_SESSION_VERSION = 1
SQL_TRANSLATION_OUTPUT_PREFIX = "-- Generated by zh-audit SQL校译"
SQL_IDENTIFIER_PATTERN = r"(?:`[^`]+`|[A-Za-z_][\w$]*)"
SQL_TABLE_PATTERN = r"(?:`[^`]+`|[A-Za-z_][\w$]*)(?:\s*\.\s*(?:`[^`]+`|[A-Za-z_][\w$]*))?"

_INSERT_TABLE_RE = re.compile(
    r"^\s*(insert|replace)\s+into\s+(?P<table>{})".format(SQL_TABLE_PATTERN),
    re.IGNORECASE | re.DOTALL,
)
_INSERT_VALUES_RE = re.compile(
    r"^\s*insert\s+into\s+(?P<table>{})\s*(?P<columns>\([^)]*\))?\s*values\b(?P<values>.*)$".format(
        SQL_TABLE_PATTERN
    ),
    re.IGNORECASE | re.DOTALL,
)
_CREATE_TABLE_RE = re.compile(
    r"^\s*create\s+table\s+(?:if\s+not\s+exists\s+)?(?P<table>{})".format(SQL_TABLE_PATTERN),
    re.IGNORECASE | re.DOTALL,
)
_ALTER_TABLE_RE = re.compile(
    r"^\s*alter\s+table\s+(?P<table>{})\s+(?P<body>.*)$".format(SQL_TABLE_PATTERN),
    re.IGNORECASE | re.DOTALL,
)


def default_sql_translation_config():
    return {
        "directory_path": "",
        "table_name": "",
        "primary_key_field": "",
        "source_field": "",
        "target_field": "",
        "schema_sql": "",
        "auto_accept": False,
    }


class SqlTranslationSession(object):
    def __init__(
        self,
        directory_path,
        table_name,
        primary_key_field,
        source_field,
        target_field,
        glossary,
        model_config,
        model_runner,
        reviewer_runner=None,
        persist_callback=None,
        rows=None,
        scan_events=None,
        schema_sql="",
        schema_source="",
        schema_error="",
    ):
        self.lock = threading.RLock()
        self.directory_path = str(directory_path)
        self.table_name = str(table_name)
        self.primary_key_field = str(primary_key_field)
        self.source_field = str(source_field)
        self.target_field = str(target_field)
        self.schema_sql = str(schema_sql or "")
        self.glossary = OrderedDict(glossary)
        self.model_config = dict(model_config)
        self.model_runner = model_runner
        self.reviewer_runner = reviewer_runner
        self.persist_callback = persist_callback
        if rows is None:
            discovered = scan_sql_translation_directory(
                directory_path=directory_path,
                table_name=table_name,
                primary_key_field=primary_key_field,
                source_field=source_field,
                target_field=target_field,
                schema_sql=schema_sql,
            )
            rows = discovered["rows"]
            scan_events = discovered["events"]
            schema_source = discovered.get("schema_source", "")
            schema_error = discovered.get("schema_error", "")
        self.rows = list(rows or [])
        self.schema_source = str(schema_source or "")
        self.schema_error = str(schema_error or "")
        self.items = OrderedDict()
        self.pending_ids = []
        self.recent_ids = []
        self.events = list(scan_events or [])
        self.total = len(self.rows)
        self.processed = 0
        self.skipped = 0
        self.pending = 0
        self.accepted = 0
        self.appended = 0
        self.failed = 0
        self.rejected = 0
        self.regenerated = 0
        self.glossary_applied = 0
        self.current = {
            "file_path": "",
            "primary_key_value": "",
            "source_text": "",
            "status": "",
        }
        self.status = "idle"
        self.message = "等待校译"
        self.error = ""
        self.started_at = ""
        self.finished_at = ""
        self.stop_requested = False
        self.next_id = 1
        self.next_index = 0
        self.output_path = ""
        self.written_item_ids = set()

    @classmethod
    def from_saved_state(
        cls,
        payload,
        glossary,
        model_config,
        model_runner,
        reviewer_runner=None,
        persist_callback=None,
    ):
        if _saved_sql_session_uses_obsolete_duplicate_reason(payload):
            raise ValueError("Saved SQL translation session uses obsolete duplicate-locator handling.")
        session = cls(
            directory_path=str(payload.get("directory_path", "") or ""),
            table_name=str(payload.get("table_name", "") or ""),
            primary_key_field=str(payload.get("primary_key_field", "") or ""),
            source_field=str(payload.get("source_field", "") or ""),
            target_field=str(payload.get("target_field", "") or ""),
            schema_sql=str(payload.get("schema_sql", "") or ""),
            glossary=glossary,
            model_config=model_config,
            model_runner=model_runner,
            reviewer_runner=reviewer_runner,
            persist_callback=persist_callback,
            rows=list(payload.get("rows", [])),
            scan_events=[],
            schema_source=str(payload.get("schema_source", "") or ""),
            schema_error=str(payload.get("schema_error", "") or ""),
        )
        session._restore_saved_state(payload)
        return session

    def start(self):
        with self.lock:
            self.status = "running"
            self.message = "校译中"
            self.error = ""
            self.started_at = _timestamp()
            self.finished_at = ""
            self.stop_requested = False
            self.next_index = 0
            self.output_path = self._build_output_path()
            self._initialize_output_file()
            self._persist_locked()

    def stop(self):
        with self.lock:
            self.stop_requested = True
            if self.status == "running":
                self.message = "停止中"
            self._persist_locked()

    def resume(self):
        with self.lock:
            if not self.can_resume():
                raise ValueError("SQL translation task cannot be resumed.")
            output_path = Path(self.output_path)
            if not output_path.exists():
                raise ValueError("SQL output file does not exist: {}".format(output_path))
            self.written_item_ids = _load_written_item_ids(output_path)
            self.status = "running"
            self.message = "校译中"
            self.error = ""
            self.finished_at = ""
            self.stop_requested = False
            if self.current.get("file_path"):
                self.current["status"] = "处理中"
            self._persist_locked()

    def can_resume(self):
        return self.status in ("interrupted", "stopped") and self.next_index < self.total

    def mark_restarted(self):
        with self.lock:
            if self.status == "running":
                self.status = "interrupted"
                self.message = "服务重启，可从上次位置继续"
                self.error = ""
                self.finished_at = _timestamp()
                if self.current.get("file_path"):
                    self.current["status"] = "等待继续"
                self.stop_requested = False
                self._persist_locked()

    def interrupt(self, error_message):
        with self.lock:
            self.status = "interrupted"
            self.message = "校译中断"
            self.error = str(error_message)
            self.finished_at = _timestamp()
            self.stop_requested = False
            if self.current.get("file_path"):
                self.current["status"] = "等待继续"
            self._persist_locked()

    def snapshot(self):
        with self.lock:
            pending_items = [self._public_item(self.items[item_id]) for item_id in self.pending_ids]
            recent_items = [self._public_item(self.items[item_id]) for item_id in self.recent_ids]
            return {
                "config": {
                    "directory_path": self.directory_path,
                    "table_name": self.table_name,
                    "primary_key_field": self.primary_key_field,
                    "source_field": self.source_field,
                    "target_field": self.target_field,
                    "schema_sql": self.schema_sql,
                },
                "status": {
                    "status": self.status,
                    "message": self.message,
                    "error": self.error,
                    "started_at": self.started_at,
                    "finished_at": self.finished_at,
                    "output_path": self.output_path,
                    "schema_source": self.schema_source,
                    "schema_error": self.schema_error,
                    "current": dict(self.current),
                    "counts": self._counts_payload(),
                },
                "pending_items": pending_items,
                "recent_items": recent_items,
                "events": list(self.events),
            }

    def save_state(self):
        with self.lock:
            return self._saved_state_locked()

    def run(self, should_auto_accept):
        while True:
            with self.lock:
                if self.stop_requested:
                    self.status = "stopped"
                    self.message = "已停止"
                    self.finished_at = _timestamp()
                    self.current = {
                        "file_path": "",
                        "primary_key_value": "",
                        "source_text": "",
                        "status": "",
                    }
                    self._persist_locked()
                    return
                if self.next_index >= self.total:
                    if self.status == "running":
                        self.status = "done"
                        self.message = "校译完成"
                        self.finished_at = _timestamp()
                        self.current = {
                            "file_path": "",
                            "primary_key_value": "",
                            "source_text": "",
                            "status": "",
                        }
                        self._persist_locked()
                    return
                row = self.rows[self.next_index]
                self.current = {
                    "file_path": row.get("source_path", ""),
                    "primary_key_value": row.get("primary_key_display", ""),
                    "source_text": row.get("source_text", ""),
                    "status": "处理中",
                }
                self._persist_locked()

            self._process_row(row, should_auto_accept)

            with self.lock:
                self.next_index += 1
                self.current = {
                    "file_path": row.get("source_path", ""),
                    "primary_key_value": row.get("primary_key_display", ""),
                    "source_text": row.get("source_text", ""),
                    "status": "已处理",
                }
                self._persist_locked()

    def accept(self, item_id, candidate_text=""):
        with self.lock:
            item = self._require_pending_item(item_id)
            manual_candidate = str(candidate_text if candidate_text is not None else "")
            reason = "人工接受（跳过系统校验）" if item.get("validation_state") == "failed" else "人工接受"
            if manual_candidate.strip():
                item["candidate_text"] = self._validated_candidate_text(item, manual_candidate)
                item["raw_candidate_text"] = manual_candidate
                reason = "手动录入后接受"
            else:
                item["candidate_text"] = self._validated_candidate_text(item)
            self._apply_item(item, "accepted", reason)
            return self.snapshot()

    def reject(self, item_id):
        with self.lock:
            item = self._require_pending_item(item_id)
            item["status"] = "rejected"
            item["updated_at"] = _timestamp()
            self.pending_ids.remove(item_id)
            self.pending -= 1
            self.rejected += 1
            self._push_recent(item_id)
            self._push_event("已忽略", item, item.get("candidate_text", ""))
            self._persist_locked()
            return self.snapshot()

    def regenerate(self, item_id, extra_prompt):
        with self.lock:
            item = self._require_pending_item(item_id)
            item["status"] = "regenerating"
            item["updated_at"] = _timestamp()
            self._persist_locked()
            source_text = item.get("source_text", "")
            target_text = item.get("target_text", "")
            locked_terms = list(item.get("locked_terms", []))
        normalized = self._build_candidate_with_guardrails(
            item={
                "source_path": item.get("source_path", ""),
                "line": item.get("line", 0),
                "table_name": item.get("table_name", self.table_name),
                "primary_key_field": item.get("primary_key_field", self.primary_key_field),
                "primary_key_display": item.get("primary_key_display", ""),
                "source_field": item.get("source_field", self.source_field),
                "source_text": source_text,
                "target_field": item.get("target_field", self.target_field),
                "target_text": target_text,
                "target_missing": item.get("target_missing", False),
                "locked_terms": locked_terms,
            },
            base_extra_prompt=extra_prompt,
        )
        with self.lock:
            self._update_item_validation(item, normalized)
            item["status"] = "pending"
            item["updated_at"] = _timestamp()
            item["regeneration_prompt"] = extra_prompt
            self.regenerated += 1
            self._push_event(self._pending_event_label(item, "已重新生成"), item, item.get("candidate_text", ""))
            self._persist_locked()
            return self.snapshot()

    def _process_row(self, row, should_auto_accept):
        skip_reason = str(row.get("skip_reason", "") or "")
        if skip_reason:
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, skip_reason)
                self._persist_locked()
            return

        source_text = str(row.get("source_text", "") or "")
        target_text = str(row.get("target_text", "") or "")
        if not source_text.strip():
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, "中文文案为空。")
                self._persist_locked()
            return

        exact_translation = exact_terminology_translation(source_text, self.glossary)
        locked_terms = match_locked_terms(source_text, self.glossary)
        if exact_translation:
            if target_text.strip() == exact_translation.strip():
                with self.lock:
                    self.processed += 1
                    self.skipped += 1
                    self.glossary_applied += 1
                    self._push_event("术语已准确", row, target_text)
                    self._persist_locked()
                return
            item = self._create_item(
                row=row,
                target_text=target_text,
                candidate_text=exact_translation,
                locked_terms=locked_terms,
                reason="整句命中术语词典。",
                verdict="needs_update",
                target_missing=not target_text.strip(),
                validation_state="passed",
                validation_message="",
                validation_issue="",
                can_accept=True,
                generation_attempts_used=0,
                model_calls_used=0,
            )
            with self.lock:
                self.glossary_applied += 1
                self._finalize_item(item, should_auto_accept=should_auto_accept(), event_label="术语命中")
            return

        normalized = self._build_candidate_with_guardrails(
            item={
                "source_path": row.get("source_path", ""),
                "line": row.get("line", 0),
                "table_name": row.get("table_name", self.table_name),
                "primary_key_field": row.get("primary_key_field", self.primary_key_field),
                "primary_key_display": row.get("primary_key_display", ""),
                "source_field": row.get("source_field", self.source_field),
                "source_text": source_text,
                "target_field": row.get("target_field", self.target_field),
                "target_text": target_text,
                "target_missing": not target_text.strip(),
                "locked_terms": locked_terms,
            },
            base_extra_prompt="",
        )
        if normalized["validation_state"] == "passed" and normalized["verdict"] == "accurate" and target_text.strip():
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, target_text)
                self._persist_locked()
            return
        item = self._create_item(
            row=row,
            target_text=target_text,
            candidate_text=normalized["candidate_text"],
            locked_terms=locked_terms,
            reason=normalized["reason"],
            verdict=normalized["verdict"],
            target_missing=not target_text.strip(),
            validation_state=normalized["validation_state"],
            validation_message=normalized["validation_message"],
            validation_issue=normalized.get("validation_issue", ""),
            can_accept=normalized["can_accept"],
            generation_attempts_used=normalized["generation_attempts_used"],
            model_calls_used=normalized["model_calls_used"],
            raw_candidate_text=normalized.get("raw_candidate_text", ""),
            raw_failure_content=normalized.get("raw_failure_content", ""),
            raw_failure_response=normalized.get("raw_failure_response", ""),
            raw_reason_text=normalized.get("raw_reason_text", ""),
            parse_error_detail=normalized.get("parse_error_detail", ""),
            failure_phase=normalized.get("failure_phase", ""),
            warnings=normalized.get("warnings", []),
            attempt_history=normalized.get("attempt_history", []),
            retry_context_preview=normalized.get("retry_context_preview", ""),
        )
        with self.lock:
            self._finalize_item(item, should_auto_accept=should_auto_accept(), event_label="待审批")

    def _build_candidate_with_guardrails(self, item, base_extra_prompt):
        generation_attempts_used = 0
        model_calls_used = 0
        retry_context = {}
        attempt_history = []
        last_result = {
            "verdict": "needs_update",
            "candidate_text": sanitize_candidate_text(item.get("target_text", "")),
            "raw_candidate_text": "",
            "raw_failure_content": "",
            "raw_failure_response": "",
            "raw_reason_text": "",
            "parse_error_detail": "",
            "failure_phase": "",
            "reason": "",
            "warnings": [],
            "attempt_history": [],
            "retry_context_preview": "",
            "validation_state": "failed",
            "validation_message": validation_message("校验未通过"),
            "validation_issue": "校验未通过",
            "can_accept": False,
            "generation_attempts_used": 0,
            "model_calls_used": 0,
        }
        while generation_attempts_used < MAX_GENERATION_ATTEMPTS_PER_ITEM:
            attempt_number = generation_attempts_used + 1
            try:
                raw_result = self.model_runner(
                    source_path=item.get("source_path", ""),
                    line=item.get("line", 0),
                    table_name=item.get("table_name", self.table_name),
                    primary_key_field=item.get("primary_key_field", self.primary_key_field),
                    primary_key_value=item.get("primary_key_display", ""),
                    source_field=item.get("source_field", self.source_field),
                    source_text=item.get("source_text", ""),
                    target_field=item.get("target_field", self.target_field),
                    target_text=item.get("target_text", ""),
                    target_missing=item.get("target_missing", False),
                    locked_terms=list(item.get("locked_terms", [])),
                    model_config=self.model_config,
                    extra_prompt=self._build_retry_prompt(base_extra_prompt, retry_context, attempt_number),
                )
            except Exception as exc:
                generation_attempts_used += 1
                model_calls_used += 1
                retry_issue = describe_retryable_model_response_error(exc, phase="模型")
                if not retry_issue:
                    raise
                debug_payload = model_response_debug_payload(exc)
                extracted_candidate = sanitize_candidate_text(debug_payload.get("extracted_candidate_text", ""))
                extracted_reason = _display_text(debug_payload.get("extracted_reason", "")).strip()
                retry_context = build_retry_context(
                    phase="model_format",
                    issue_code="model_format_invalid",
                    issue_message=retry_issue,
                    previous_candidate=extracted_candidate or sanitize_candidate_text(item.get("target_text", "")),
                    source_text=item.get("source_text", ""),
                    locked_terms=list(item.get("locked_terms", [])),
                    candidate_text=extracted_candidate or sanitize_candidate_text(item.get("target_text", "")),
                )
                attempt_history.append(
                    build_attempt_history_entry(
                        generation_attempts_used,
                        extracted_candidate or sanitize_candidate_text(item.get("target_text", "")),
                        failure_phase="模型",
                        failure_issue=retry_issue,
                        reason=extracted_reason,
                        retry_context=retry_context,
                    )
                )
                last_result = {
                    "verdict": "needs_update",
                    "candidate_text": extracted_candidate or sanitize_candidate_text(item.get("target_text", "")),
                    "raw_candidate_text": extracted_candidate,
                    "raw_failure_content": _display_text(debug_payload.get("raw_content", "")).strip(),
                    "raw_failure_response": _display_text(debug_payload.get("raw_response", "")).strip(),
                    "raw_reason_text": extracted_reason,
                    "parse_error_detail": _display_text(debug_payload.get("parse_error_detail", "")).strip(),
                    "failure_phase": "模型",
                    "reason": extracted_reason,
                    "warnings": [],
                    "attempt_history": list(attempt_history),
                    "retry_context_preview": retry_context_preview(retry_context),
                    "validation_state": "failed",
                    "validation_message": validation_message(retry_issue),
                    "validation_issue": retry_issue,
                    "can_accept": False,
                    "generation_attempts_used": generation_attempts_used,
                    "model_calls_used": model_calls_used,
                }
                continue
            generation_attempts_used += 1
            model_calls_used += 1
            normalized = self._normalize_model_result(item, raw_result, item.get("target_text", ""))
            candidate_text = normalized["candidate_text"]
            raw_candidate_text = _display_text(raw_result.get("candidate_translation", "")).strip()
            validation_issue = validate_candidate_text(
                item.get("source_text", ""),
                candidate_text,
                raw_candidate_text=raw_result.get("candidate_translation", candidate_text),
                locked_terms=list(item.get("locked_terms", [])),
                check_sql_pollution=True,
                enforce_placeholders=True,
            )
            if validation_issue:
                retry_context = build_validation_retry_context(
                    item.get("source_text", ""),
                    candidate_text,
                    list(item.get("locked_terms", [])),
                    validation_issue,
                )
                attempt_history.append(
                    build_attempt_history_entry(
                        generation_attempts_used,
                        candidate_text,
                        failure_phase="本地校验",
                        failure_issue=validation_issue,
                        reason=normalized["reason"],
                        retry_context=retry_context,
                    )
                )
                last_result = {
                    "verdict": "needs_update",
                    "candidate_text": candidate_text,
                    "raw_candidate_text": raw_candidate_text,
                    "raw_failure_content": "",
                    "raw_failure_response": "",
                    "raw_reason_text": "",
                    "parse_error_detail": "",
                    "failure_phase": "本地校验",
                    "reason": normalized["reason"],
                    "warnings": [],
                    "attempt_history": list(attempt_history),
                    "retry_context_preview": retry_context_preview(retry_context),
                    "validation_state": "failed",
                    "validation_message": validation_message(validation_issue),
                    "validation_issue": validation_issue,
                    "can_accept": False,
                    "generation_attempts_used": generation_attempts_used,
                    "model_calls_used": model_calls_used,
                }
                continue
            if self.reviewer_runner is not None:
                try:
                    review_result = self.reviewer_runner(
                        source_path=item.get("source_path", ""),
                        line=item.get("line", 0),
                        table_name=item.get("table_name", self.table_name),
                        primary_key_field=item.get("primary_key_field", self.primary_key_field),
                        primary_key_value=item.get("primary_key_display", ""),
                        source_field=item.get("source_field", self.source_field),
                        source_text=item.get("source_text", ""),
                        target_field=item.get("target_field", self.target_field),
                        candidate_text=candidate_text,
                        target_missing=item.get("target_missing", False),
                        locked_terms=list(item.get("locked_terms", [])),
                        model_config=self.model_config,
                        extra_prompt=base_extra_prompt,
                    )
                except Exception as exc:
                    model_calls_used += 1
                    retry_issue = describe_retryable_model_response_error(exc, phase="AI复核")
                    if not retry_issue:
                        raise
                    debug_payload = model_response_debug_payload(exc)
                    extracted_reason = _display_text(debug_payload.get("extracted_reason", "")).strip()
                    retry_context = build_retry_context(
                        phase="model_format",
                        issue_code="review_model_format_invalid",
                        issue_message=retry_issue,
                        previous_candidate=candidate_text,
                        source_text=item.get("source_text", ""),
                        locked_terms=list(item.get("locked_terms", [])),
                        candidate_text=candidate_text,
                    )
                    attempt_history.append(
                        build_attempt_history_entry(
                            generation_attempts_used,
                            candidate_text,
                            failure_phase="AI复核",
                            failure_issue=retry_issue,
                            reason=extracted_reason or normalized["reason"],
                            retry_context=retry_context,
                        )
                    )
                    last_result = {
                        "verdict": "needs_update",
                        "candidate_text": candidate_text,
                        "raw_candidate_text": raw_candidate_text,
                        "raw_failure_content": _display_text(debug_payload.get("raw_content", "")).strip(),
                        "raw_failure_response": _display_text(debug_payload.get("raw_response", "")).strip(),
                        "raw_reason_text": extracted_reason,
                        "parse_error_detail": _display_text(debug_payload.get("parse_error_detail", "")).strip(),
                        "failure_phase": "AI复核",
                        "reason": extracted_reason or normalized["reason"],
                        "warnings": [],
                        "attempt_history": list(attempt_history),
                        "retry_context_preview": retry_context_preview(retry_context),
                        "validation_state": "failed",
                        "validation_message": validation_message(retry_issue),
                        "validation_issue": retry_issue,
                        "can_accept": False,
                        "generation_attempts_used": generation_attempts_used,
                        "model_calls_used": model_calls_used,
                    }
                    continue
                model_calls_used += 1
                reviewed = normalize_review_result(
                    review_result,
                    source_text=item.get("source_text", ""),
                    candidate_text=candidate_text,
                    locked_terms=list(item.get("locked_terms", [])),
                )
                warning_messages = list(reviewed.get("warnings", []))
                if reviewed["decision"] != "pass":
                    retry_issue = reviewed["issues"][0]
                    retry_context = build_review_retry_context(
                        item.get("source_text", ""),
                        candidate_text,
                        list(item.get("locked_terms", [])),
                        (reviewed.get("issue_details") or [{}])[0],
                        reviewed.get("warning_details", []),
                    )
                    attempt_history.append(
                        build_attempt_history_entry(
                            generation_attempts_used,
                            candidate_text,
                            failure_phase="AI复核",
                            failure_issue=retry_issue,
                            warnings=warning_messages,
                            reason=normalized["reason"],
                            retry_context=retry_context,
                        )
                    )
                    last_result = {
                        "verdict": "needs_update",
                        "candidate_text": candidate_text,
                        "raw_candidate_text": raw_candidate_text,
                        "raw_failure_content": "",
                        "raw_failure_response": "",
                        "raw_reason_text": "",
                        "parse_error_detail": "",
                        "failure_phase": "AI复核",
                        "reason": normalized["reason"],
                        "warnings": warning_messages,
                        "attempt_history": list(attempt_history),
                        "retry_context_preview": retry_context_preview(retry_context),
                        "validation_state": "failed",
                        "validation_message": validation_message(retry_issue),
                        "validation_issue": retry_issue,
                        "can_accept": False,
                        "generation_attempts_used": generation_attempts_used,
                        "model_calls_used": model_calls_used,
                    }
                    continue
            else:
                warning_messages = []
            attempt_history.append(
                build_attempt_history_entry(
                    generation_attempts_used,
                    candidate_text,
                    warnings=warning_messages,
                    reason=normalized["reason"],
                )
            )
            return {
                "verdict": normalized["verdict"],
                "candidate_text": candidate_text,
                "raw_candidate_text": raw_candidate_text,
                "raw_failure_content": "",
                "raw_failure_response": "",
                "raw_reason_text": "",
                "parse_error_detail": "",
                "failure_phase": "",
                "reason": normalized["reason"],
                "warnings": warning_messages,
                "attempt_history": list(attempt_history),
                "retry_context_preview": "",
                "validation_state": "passed",
                "validation_message": "",
                "validation_issue": "",
                "can_accept": True,
                "generation_attempts_used": generation_attempts_used,
                "model_calls_used": model_calls_used,
            }
        failure_issue = last_result.get("validation_issue") or "校验未通过"
        last_result["validation_state"] = "failed"
        last_result["validation_message"] = exhausted_validation_message(
            failure_issue,
            generation_attempts_used or MAX_GENERATION_ATTEMPTS_PER_ITEM,
        )
        last_result["validation_issue"] = failure_issue
        last_result["can_accept"] = False
        last_result["generation_attempts_used"] = min(
            generation_attempts_used,
            MAX_GENERATION_ATTEMPTS_PER_ITEM,
        )
        last_result["model_calls_used"] = model_calls_used
        return last_result

    def _normalize_model_result(self, item, result, current_target):
        verdict = str(result.get("verdict", "") or "").strip().lower()
        candidate = sanitize_candidate_text(result.get("candidate_translation", ""))
        reason = _display_text(result.get("reason", "")).strip()
        if verdict not in ("accurate", "needs_update"):
            verdict = "needs_update"
        locked_terms = list(item.get("locked_terms", []))
        target_missing = bool(item.get("target_missing", not str(current_target or "").strip()))
        if verdict == "accurate" and target_missing:
            verdict = "needs_update"
        if verdict == "accurate":
            if locked_terms and not contains_locked_terms(current_target, locked_terms):
                verdict = "needs_update"
                reason = "现有英文未满足术语词典要求。"
            else:
                return {
                    "verdict": verdict,
                    "candidate_text": sanitize_candidate_text(current_target),
                    "reason": _normalize_reason(reason, fallback="现有英文准确。"),
                }
        if not candidate:
            raise ValueError(
                "Model did not return candidate_translation for SQL item {}".format(item.get("primary_key_display", ""))
            )
        return {
            "verdict": "needs_update",
            "candidate_text": candidate,
            "reason": _normalize_reason(
                reason,
                fallback="目标英文缺失，建议补充候选英文。" if target_missing else "模型建议更新英文翻译。",
            ),
        }

    def _build_retry_prompt(self, base_extra_prompt, retry_context, attempt_number):
        return structured_retry_prompt(base_extra_prompt, retry_context, attempt_number)

    def _create_item(
        self,
        row,
        target_text,
        candidate_text,
        locked_terms,
        reason,
        verdict,
        target_missing,
        validation_state,
        validation_message,
        validation_issue,
        can_accept,
        generation_attempts_used,
        model_calls_used,
        raw_candidate_text="",
        raw_failure_content="",
        raw_failure_response="",
        raw_reason_text="",
        parse_error_detail="",
        failure_phase="",
        warnings=None,
        attempt_history=None,
        retry_context_preview="",
    ):
        with self.lock:
            item_id = "sql-{}".format(self.next_id)
            self.next_id += 1
            item = {
                "id": item_id,
                "source_path": row.get("source_path", ""),
                "line": int(row.get("line", 0) or 0),
                "table_expression": row.get("table_expression", ""),
                "table_name": row.get("table_name", self.table_name),
                "primary_key_field_sql": row.get("primary_key_field_sql", self.primary_key_field),
                "primary_key_field": row.get("primary_key_field", self.primary_key_field),
                "primary_key_literal": row.get("primary_key_literal", ""),
                "primary_key_display": row.get("primary_key_display", ""),
                "source_field": row.get("source_field", self.source_field),
                "source_text": row.get("source_text", ""),
                "target_field_sql": row.get("target_field_sql", self.target_field),
                "target_field": row.get("target_field", self.target_field),
                "target_text": target_text,
                "candidate_text": candidate_text,
                "raw_candidate_text": str(raw_candidate_text or ""),
                "raw_failure_content": str(raw_failure_content or ""),
                "raw_failure_response": str(raw_failure_response or ""),
                "raw_reason_text": str(raw_reason_text or ""),
                "parse_error_detail": str(parse_error_detail or ""),
                "failure_phase": str(failure_phase or ""),
                "warnings": [str(message or "").strip() for message in (warnings or []) if str(message or "").strip()],
                "attempt_history": [dict(entry) for entry in (attempt_history or [])],
                "retry_context_preview": str(retry_context_preview or ""),
                "locked_terms": [dict(term) for term in locked_terms],
                "reason": reason,
                "verdict": verdict,
                "target_missing": bool(target_missing),
                "validation_state": str(validation_state or "passed"),
                "validation_message": str(validation_message or ""),
                "validation_issue": str(validation_issue or ""),
                "can_accept": bool(can_accept),
                "generation_attempts_used": int(generation_attempts_used or 0),
                "model_calls_used": int(model_calls_used or 0),
                "status": "pending",
                "updated_at": _timestamp(),
            }
            self.items[item_id] = item
            self._persist_locked()
            return item

    def _update_item_validation(self, item, normalized):
        item["candidate_text"] = normalized["candidate_text"]
        item["raw_candidate_text"] = str(normalized.get("raw_candidate_text", ""))
        item["raw_failure_content"] = str(normalized.get("raw_failure_content", ""))
        item["raw_failure_response"] = str(normalized.get("raw_failure_response", ""))
        item["raw_reason_text"] = str(normalized.get("raw_reason_text", ""))
        item["parse_error_detail"] = str(normalized.get("parse_error_detail", ""))
        item["failure_phase"] = str(normalized.get("failure_phase", ""))
        item["warnings"] = [str(message or "").strip() for message in normalized.get("warnings", []) if str(message or "").strip()]
        item["attempt_history"] = [dict(entry) for entry in normalized.get("attempt_history", [])]
        item["retry_context_preview"] = str(normalized.get("retry_context_preview", ""))
        item["reason"] = normalized["reason"]
        item["verdict"] = normalized["verdict"]
        item["validation_state"] = normalized["validation_state"]
        item["validation_message"] = normalized["validation_message"]
        item["validation_issue"] = normalized.get("validation_issue", "")
        item["can_accept"] = bool(normalized["can_accept"])
        item["generation_attempts_used"] = int(normalized.get("generation_attempts_used", item.get("generation_attempts_used", 0)) or 0)
        item["model_calls_used"] = int(normalized["model_calls_used"])

    def _finalize_item(self, item, should_auto_accept, event_label):
        self.processed += 1
        if should_auto_accept and item.get("can_accept", True):
            self._apply_item(item, "accepted", "已自动审批")
            return
        item["status"] = "pending"
        item["updated_at"] = _timestamp()
        self.pending_ids.append(item["id"])
        self.pending += 1
        if item.get("validation_state") == "failed":
            self.failed += 1
        self._push_event(self._pending_event_label(item, event_label), item, item.get("candidate_text", ""))
        self._persist_locked()

    def _validated_candidate_text(self, item, candidate_text=None):
        value = sanitize_candidate_text(
            item.get("candidate_text", "") if candidate_text is None else candidate_text
        )
        if not value:
            raise ValueError("Candidate translation is empty for SQL item {}".format(item.get("primary_key_display", "")))
        if not has_matching_placeholders(item.get("source_text", ""), value):
            raise ValueError(
                "Candidate translation lost placeholders for SQL item {}".format(item.get("primary_key_display", ""))
            )
        return value

    def _apply_item(self, item, status, reason):
        item["candidate_text"] = self._validated_candidate_text(item)
        appended = self._append_update_sql_once(item)
        item["status"] = status
        item["target_text"] = item.get("candidate_text", "")
        item["updated_at"] = _timestamp()
        item["accepted_reason"] = reason
        if item["id"] in self.pending_ids:
            self.pending_ids.remove(item["id"])
            self.pending -= 1
        self.accepted += 1
        if appended:
            self.appended += 1
        self._push_recent(item["id"])
        self._push_event(reason, item, item.get("candidate_text", ""))
        self._persist_locked()

    def _pending_event_label(self, item, default_label):
        if item.get("validation_state") == "failed":
            phase = str(item.get("failure_phase", "") or "本地校验")
            if phase == "模型":
                prefix = "候选生成失败"
            elif phase == "AI复核":
                prefix = "候选通过 AI复核失败"
            else:
                prefix = "候选通过本地校验失败"
            return "{}：{}".format(prefix, item.get("validation_issue") or "请重新生成")
        return default_label

    def _append_update_sql_once(self, item):
        item_id = item["id"]
        if item_id in self.written_item_ids:
            return False
        output_path = Path(self.output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        rendered = "\n".join(
            [
                "-- item:{}".format(item_id),
                "-- source:{}:{}".format(item.get("source_path", ""), item.get("line", 0)),
                _build_update_sql(item),
                "",
            ]
        )
        with output_path.open("a", encoding="utf-8") as handle:
            handle.write(rendered)
        self.written_item_ids.add(item_id)
        return True

    def _initialize_output_file(self):
        output_path = Path(self.output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        header = "\n".join(
            [
                SQL_TRANSLATION_OUTPUT_PREFIX,
                "-- table: {}".format(self.table_name),
                "-- locator_field: {}".format(self.primary_key_field),
                "-- source_field: {}".format(self.source_field),
                "-- target_field: {}".format(self.target_field),
                "-- source_directory: {}".format(self.directory_path),
                "-- created_at: {}".format(_timestamp()),
                "",
            ]
        )
        output_path.write_text(header, encoding="utf-8")
        self.written_item_ids = set()

    def _build_output_path(self):
        directory = Path(self.directory_path)
        safe_table = _safe_file_name_component(self.table_name or "table")
        file_name = "{}_sql_audit_{}.sql".format(safe_table, datetime.now().strftime("%Y%m%d_%H%M%S"))
        return str((directory / file_name).resolve())

    def _push_recent(self, item_id):
        if item_id in self.recent_ids:
            self.recent_ids.remove(item_id)
        self.recent_ids.insert(0, item_id)
        del self.recent_ids[50:]

    def _push_event(self, label, item, detail):
        skip_reason = ""
        if label == "已跳过":
            skip_reason = str(item.get("skip_reason", "") or item.get("reason", "") or "")
        self.events.insert(
            0,
            {
                "at": _timestamp(),
                "label": label,
                "source_path": item.get("source_path", ""),
                "line": item.get("line", 0),
                "primary_key_value": item.get("primary_key_display", ""),
                "source_text": item.get("source_text", ""),
                "target_text": detail,
                "reason": skip_reason,
                "parse_phase": item.get("parse_phase", ""),
                "statement_preview": item.get("statement_preview", ""),
            },
        )
        del self.events[100:]

    def _public_item(self, item):
        return {
            "id": item["id"],
            "source_path": item.get("source_path", ""),
            "line": item.get("line", 0),
            "primary_key_value": item.get("primary_key_display", ""),
            "source_text": item.get("source_text", ""),
            "target_text": item.get("target_text", ""),
            "candidate_text": item.get("candidate_text", ""),
            "raw_candidate_text": item.get("raw_candidate_text", ""),
            "raw_failure_content": item.get("raw_failure_content", ""),
            "raw_failure_response": item.get("raw_failure_response", ""),
            "raw_reason_text": item.get("raw_reason_text", ""),
            "parse_error_detail": item.get("parse_error_detail", ""),
            "failure_phase": item.get("failure_phase", ""),
            "warnings": list(item.get("warnings", [])),
            "attempt_history": [dict(entry) for entry in item.get("attempt_history", [])],
            "retry_context_preview": item.get("retry_context_preview", ""),
            "locked_terms": [dict(term) for term in item.get("locked_terms", [])],
            "reason": item.get("reason", ""),
            "verdict": item.get("verdict", ""),
            "status": item.get("status", ""),
            "target_missing": bool(item.get("target_missing", False)),
            "validation_state": item.get("validation_state", "passed"),
            "validation_message": item.get("validation_message", ""),
            "can_accept": bool(item.get("can_accept", True)),
            "generation_attempts_used": int(item.get("generation_attempts_used", item.get("model_calls_used", 0)) or 0),
            "model_calls_used": int(item.get("model_calls_used", 0) or 0),
            "updated_at": item.get("updated_at", ""),
        }

    def _require_pending_item(self, item_id):
        item = self.items.get(item_id)
        if item is None:
            raise KeyError("Unknown SQL translation item: {}".format(item_id))
        if item.get("status") != "pending":
            raise ValueError("SQL translation item is not pending: {}".format(item_id))
        return item

    def _counts_payload(self):
        return {
            "total": self.total,
            "processed": self.processed,
            "skipped": self.skipped,
            "pending": self.pending,
            "accepted": self.accepted,
            "appended": self.appended,
            "failed": self.failed,
            "rejected": self.rejected,
            "regenerated": self.regenerated,
            "glossary_applied": self.glossary_applied,
        }

    def _saved_state_locked(self):
        return {
            "version": SQL_TRANSLATION_SESSION_VERSION,
            "directory_path": self.directory_path,
            "table_name": self.table_name,
            "primary_key_field": self.primary_key_field,
            "source_field": self.source_field,
            "target_field": self.target_field,
            "schema_sql": self.schema_sql,
            "schema_source": self.schema_source,
            "schema_error": self.schema_error,
            "rows": list(self.rows),
            "counts": self._counts_payload(),
            "items": [dict(item) for item in self.items.values()],
            "pending_ids": list(self.pending_ids),
            "recent_ids": list(self.recent_ids),
            "events": list(self.events),
            "current": dict(self.current),
            "status": self.status,
            "message": self.message,
            "error": self.error,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "stop_requested": bool(self.stop_requested),
            "next_id": self.next_id,
            "next_index": self.next_index,
            "output_path": self.output_path,
            "written_item_ids": sorted(self.written_item_ids),
        }

    def _restore_saved_state(self, payload):
        counts = dict(payload.get("counts", {}))
        self.rows = list(payload.get("rows", self.rows))
        self.total = len(self.rows)
        self.schema_sql = str(payload.get("schema_sql", self.schema_sql) or "")
        self.schema_source = str(payload.get("schema_source", self.schema_source) or "")
        self.schema_error = str(payload.get("schema_error", self.schema_error) or "")
        self.items = OrderedDict()
        for item in payload.get("items", []):
            item_id = str(item.get("id", "") or "")
            if not item_id:
                continue
            restored = dict(item)
            restored["id"] = item_id
            restored.setdefault("validation_state", "passed")
            restored.setdefault("validation_message", "")
            restored.setdefault("validation_issue", "")
            restored.setdefault("raw_candidate_text", "")
            restored.setdefault("raw_failure_content", "")
            restored.setdefault("raw_failure_response", "")
            restored.setdefault("raw_reason_text", "")
            restored.setdefault("parse_error_detail", "")
            restored.setdefault("failure_phase", "")
            restored.setdefault("warnings", [])
            restored.setdefault("attempt_history", [])
            restored.setdefault("retry_context_preview", "")
            restored.setdefault("can_accept", True)
            restored.setdefault(
                "generation_attempts_used",
                min(int(restored.get("model_calls_used", 0) or 0), MAX_GENERATION_ATTEMPTS_PER_ITEM),
            )
            restored.setdefault("model_calls_used", 0)
            self.items[item_id] = restored
        self.pending_ids = [item_id for item_id in payload.get("pending_ids", []) if item_id in self.items]
        self.recent_ids = [item_id for item_id in payload.get("recent_ids", []) if item_id in self.items]
        self.events = list(payload.get("events", []))
        self.processed = int(counts.get("processed", 0))
        self.skipped = int(counts.get("skipped", 0))
        self.pending = int(counts.get("pending", len(self.pending_ids)))
        self.accepted = int(counts.get("accepted", 0))
        self.appended = int(counts.get("appended", 0))
        self.failed = int(counts.get("failed", 0))
        self.rejected = int(counts.get("rejected", 0))
        self.regenerated = int(counts.get("regenerated", 0))
        self.glossary_applied = int(counts.get("glossary_applied", 0))
        self.current = dict(payload.get("current", {}))
        self.status = str(payload.get("status", "idle") or "idle")
        self.message = str(payload.get("message", "等待校译") or "等待校译")
        self.error = str(payload.get("error", "") or "")
        self.started_at = str(payload.get("started_at", "") or "")
        self.finished_at = str(payload.get("finished_at", "") or "")
        self.stop_requested = bool(payload.get("stop_requested", False))
        self.next_id = max(int(payload.get("next_id", 1)), 1)
        try:
            next_index = int(payload.get("next_index", self.processed))
        except (TypeError, ValueError):
            next_index = self.processed
        self.next_index = min(max(next_index, 0), self.total)
        self.output_path = str(payload.get("output_path", "") or "")
        self.written_item_ids = set(payload.get("written_item_ids", []))
        if self.output_path:
            output_path = Path(self.output_path)
            if output_path.exists():
                self.written_item_ids = _load_written_item_ids(output_path)
        if self.status == "running":
            self.status = "interrupted"
            self.message = "服务重启，可从上次位置继续"
            self.error = ""
            self.finished_at = _timestamp()
            if self.current.get("file_path"):
                self.current["status"] = "等待继续"
            self.stop_requested = False

    def _persist_locked(self):
        if self.persist_callback is None:
            return
        self.persist_callback(self._saved_state_locked())


def scan_sql_translation_directory(directory_path, table_name, primary_key_field, source_field, target_field, schema_sql=""):
    directory = Path(directory_path).expanduser()
    schema_result = infer_sql_translation_schema(
        directory_path=directory,
        table_name=table_name,
        schema_sql=schema_sql,
    )
    rows = []
    events = list(schema_result.get("events", []))
    for path in sorted(directory.rglob("*.sql")):
        parsed = parse_sql_translation_file(
            path=path,
            table_name=table_name,
            primary_key_field=primary_key_field,
            source_field=source_field,
            target_field=target_field,
            inferred_columns=schema_result.get("columns", []),
            schema_source=schema_result.get("source", ""),
            schema_error=schema_result.get("error", ""),
        )
        rows.extend(parsed["rows"])
        events.extend(parsed["events"])
    duplicates = {}
    for row in rows:
        key = row.get("primary_key_literal", "")
        if not key or row.get("skip_reason"):
            continue
        duplicates.setdefault(key, []).append(row)
    for duplicate_rows in duplicates.values():
        if len(duplicate_rows) < 2:
            continue
        ordered_rows = sorted(duplicate_rows, key=_sql_row_precedence_key)
        latest_row = ordered_rows[-1]
        for row in ordered_rows[:-1]:
            row["skip_reason"] = (
                "定位字段值重复，已按脚本顺序保留较新的语句：{}:{}".format(
                    latest_row.get("source_path", ""),
                    latest_row.get("line", 0),
                )
            )
    return {
        "rows": rows,
        "events": events,
        "schema_source": schema_result.get("source", ""),
        "schema_error": schema_result.get("error", ""),
    }


def parse_sql_translation_file(
    path,
    table_name,
    primary_key_field,
    source_field,
    target_field,
    inferred_columns=None,
    schema_source="",
    schema_error="",
):
    sql_path = Path(path)
    text = sql_path.read_text(encoding="utf-8")
    masked = _mask_sql_comments(text)
    statements = _split_sql_statements(text, masked)
    rows = []
    events = []
    target_table_name = _normalize_identifier(table_name)
    target_primary = _normalize_identifier(primary_key_field)
    target_source = _normalize_identifier(source_field)
    target_target = _normalize_identifier(target_field)
    inferred_columns = list(inferred_columns or [])
    for statement in statements:
        original = statement["text"]
        masked_text = statement["masked_text"]
        table_match = _INSERT_TABLE_RE.match(masked_text)
        if table_match is None:
            continue
        table_expression = original[table_match.start("table"):table_match.end("table")].strip()
        if _normalize_identifier(_table_leaf_name(table_expression)) != target_table_name:
            continue
        if str(table_match.group(1) or "").strip().lower() == "replace":
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "REPLACE INTO 暂不支持。",
                    statement_text=original,
                    parse_phase="语句类型",
                )
            )
            continue
        values_match = _INSERT_VALUES_RE.match(masked_text)
        if values_match is None:
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "仅支持 INSERT ... VALUES 语句。",
                    statement_text=original,
                    parse_phase="INSERT 结构",
                )
            )
            continue
        uses_inferred_schema = values_match.group("columns") is None
        if uses_inferred_schema:
            if not inferred_columns:
                missing_reason = "INSERT 未写列名，且未能推导当前表结构，请粘贴当前建表 SQL。"
                if schema_error:
                    missing_reason = "{} 推导失败原因：{}".format(missing_reason, schema_error)
                events.append(
                    _build_scan_event(
                        sql_path,
                        statement["line"],
                        missing_reason,
                        statement_text=original,
                        parse_phase="DDL 自动推导",
                    )
                )
                continue
            columns = [dict(column) for column in inferred_columns]
        else:
            columns_text = original[values_match.start("columns"):values_match.end("columns")]
            columns = _parse_identifier_list(columns_text)
        column_map = {}
        for column in columns:
            column_map[column["normalized"]] = column["raw"]
        if target_primary not in column_map:
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "当前表结构缺少定位字段。"
                    if uses_inferred_schema
                    else "INSERT 语句缺少定位字段。",
                    statement_text=original,
                    parse_phase="字段匹配" if not uses_inferred_schema else "表结构映射",
                )
            )
            continue
        if target_source not in column_map:
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "当前表结构缺少中文文案字段。"
                    if uses_inferred_schema
                    else "INSERT 语句缺少中文文案字段。",
                    statement_text=original,
                    parse_phase="字段匹配" if not uses_inferred_schema else "表结构映射",
                )
            )
            continue
        if target_target not in column_map:
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "当前表结构缺少英文文案字段。"
                    if uses_inferred_schema
                    else "INSERT 语句缺少英文文案字段。",
                    statement_text=original,
                    parse_phase="字段匹配" if not uses_inferred_schema else "表结构映射",
                )
            )
            continue
        values_text = original[values_match.start("values"):values_match.end("values")]
        values_line = statement["line"] + original[:values_match.start("values")].count("\n")
        groups = _parse_values_groups(values_text, values_line)
        if not groups:
            events.append(
                _build_scan_event(
                    sql_path,
                    statement["line"],
                    "未解析到 VALUES 元组。",
                    statement_text=original,
                    parse_phase="VALUES 解析",
                )
            )
            continue
        for group in groups:
            tokens = _split_tuple_values(group["text"])
            if len(tokens) != len(columns):
                rows.append(
                    {
                        "source_path": str(sql_path),
                        "line": group["line"],
                        "table_expression": table_expression,
                        "table_name": table_name,
                        "primary_key_field": primary_key_field,
                        "primary_key_field_sql": column_map[target_primary],
                        "primary_key_literal": "",
                        "primary_key_display": "",
                        "source_field": source_field,
                        "source_text": "",
                        "target_field": target_field,
                        "target_field_sql": column_map[target_target],
                        "target_text": "",
                    "skip_reason": "VALUES 元组字段数与列数不一致。",
                        "parse_phase": "VALUES 解析" if not uses_inferred_schema else "表结构映射",
                        "statement_preview": _preview_sql_statement(original),
                    }
                )
                continue
            resolved = {}
            for index, column in enumerate(columns):
                resolved[column["normalized"]] = tokens[index].strip()
            primary_key_literal = resolved.get(target_primary, "")
            source_token = resolved.get(target_source, "")
            target_token = resolved.get(target_target, "")
            rows.append(
                {
                    "source_path": str(sql_path),
                    "line": group["line"],
                    "table_expression": table_expression,
                    "table_name": table_name,
                    "primary_key_field": primary_key_field,
                    "primary_key_field_sql": column_map[target_primary],
                    "primary_key_literal": primary_key_literal,
                    "primary_key_display": _sql_value_to_display(primary_key_literal),
                    "source_field": source_field,
                    "source_text": _sql_value_to_text(source_token),
                    "target_field": target_field,
                    "target_field_sql": column_map[target_target],
                    "target_text": _sql_value_to_text(target_token),
                    "skip_reason": "",
                    "schema_source": schema_source if uses_inferred_schema else "",
                }
            )
    return {
        "rows": rows,
        "events": events,
    }


def infer_sql_translation_schema(directory_path, table_name, schema_sql=""):
    manual_schema = str(schema_sql or "").strip()
    if manual_schema:
        return _infer_schema_from_manual_sql(table_name, manual_schema)
    return _infer_schema_from_directory(directory_path, table_name)


def _infer_schema_from_manual_sql(table_name, schema_sql):
    pseudo_path = "手工建表 SQL"
    text = str(schema_sql or "")
    masked = _mask_sql_comments(text)
    statements = _split_sql_statements(text, masked)
    entries = _collect_schema_entries(statements, pseudo_path, table_name)
    result = _resolve_schema_entries(entries, table_name, "手工建表 SQL")
    if result["error"]:
        fallback_error = "手工建表 SQL 无法解析，请检查后重试。"
        if not result["events"]:
            result["events"] = [
                _build_scan_event(
                    pseudo_path,
                    1,
                    fallback_error,
                    statement_text=text,
                    parse_phase="DDL 自动推导",
                )
            ]
        result["error"] = result["error"] or fallback_error
    return result


def _infer_schema_from_directory(directory_path, table_name):
    directory = Path(directory_path).expanduser()
    entries = []
    for path in sorted(directory.rglob("*.sql")):
        text = path.read_text(encoding="utf-8")
        masked = _mask_sql_comments(text)
        statements = _split_sql_statements(text, masked)
        entries.extend(_collect_schema_entries(statements, path, table_name))
    return _resolve_schema_entries(entries, table_name, "目录自动推导")


def _collect_schema_entries(statements, source_path, table_name):
    target_table_name = _normalize_identifier(table_name)
    entries = []
    for statement in statements:
        original = statement["text"]
        masked_text = statement["masked_text"]
        create_match = _CREATE_TABLE_RE.match(masked_text)
        if create_match is not None:
            table_expression = original[create_match.start("table"):create_match.end("table")].strip()
            if _normalize_identifier(_table_leaf_name(table_expression)) == target_table_name:
                entries.append(
                    {
                        "kind": "create",
                        "path": str(source_path),
                        "line": int(statement["line"]),
                        "text": original,
                    }
                )
            continue
        alter_match = _ALTER_TABLE_RE.match(masked_text)
        if alter_match is None:
            continue
        table_expression = original[alter_match.start("table"):alter_match.end("table")].strip()
        if _normalize_identifier(_table_leaf_name(table_expression)) != target_table_name:
            continue
        entries.append(
            {
                "kind": "alter",
                "path": str(source_path),
                "line": int(statement["line"]),
                "text": original,
            }
        )
    return entries


def _resolve_schema_entries(entries, table_name, source_label):
    create_entries = [entry for entry in entries if entry["kind"] == "create"]
    if not create_entries:
        return {
            "columns": [],
            "source": "",
            "error": "未找到目标表 CREATE TABLE，请粘贴当前建表 SQL。",
            "events": [
                _build_scan_event(
                    entries[0]["path"] if entries else "",
                    entries[0]["line"] if entries else 0,
                    "未找到目标表 CREATE TABLE，请粘贴当前建表 SQL。",
                    statement_text=entries[0]["text"] if entries else "",
                    parse_phase="DDL 自动推导",
                )
            ],
        }
    if len(create_entries) > 1:
        first = create_entries[0]
        return {
            "columns": [],
            "source": "",
            "error": "找到多份目标表 CREATE TABLE，无法可靠推导当前表结构，请粘贴当前建表 SQL。",
            "events": [
                _build_scan_event(
                    first["path"],
                    first["line"],
                    "找到多份目标表 CREATE TABLE，无法可靠推导当前表结构，请粘贴当前建表 SQL。",
                    statement_text=first["text"],
                    parse_phase="DDL 自动推导",
                )
            ],
        }

    create_entry = create_entries[0]
    try:
        columns = _parse_create_table_columns(create_entry["text"], table_name)
    except ValueError as exc:
        return {
            "columns": [],
            "source": "",
            "error": str(exc),
            "events": [
                _build_scan_event(
                    create_entry["path"],
                    create_entry["line"],
                    str(exc),
                    statement_text=create_entry["text"],
                    parse_phase="DDL 自动推导",
                )
            ],
        }

    for entry in entries:
        if entry["kind"] != "alter":
            continue
        try:
            columns = _apply_alter_table_statement(columns, entry["text"], table_name)
        except ValueError as exc:
            return {
                "columns": [],
                "source": "",
                "error": str(exc),
                "events": [
                    _build_scan_event(
                        entry["path"],
                        entry["line"],
                        str(exc),
                        statement_text=entry["text"],
                        parse_phase="DDL 自动推导",
                    )
                ],
            }

    success_detail = "来源：{}；已推导 {} 个字段。".format(source_label, len(columns))
    success_event = _build_info_event(
        create_entry["path"],
        create_entry["line"],
        "Schema 已就绪",
        success_detail,
        parse_phase="DDL 自动推导",
    )
    return {
        "columns": columns,
        "source": source_label,
        "error": "",
        "events": [success_event],
    }


def _parse_create_table_columns(statement_text, table_name):
    masked_text = _mask_sql_comments(statement_text)
    match = _CREATE_TABLE_RE.match(masked_text)
    if match is None:
        raise ValueError("手工建表 SQL 不是目标表的 CREATE TABLE 语句。")
    table_expression = statement_text[match.start("table"):match.end("table")].strip()
    if _normalize_identifier(_table_leaf_name(table_expression)) != _normalize_identifier(table_name):
        raise ValueError("手工建表 SQL 中的表名与目标表名不一致。")
    start = masked_text.find("(", match.end("table"))
    if start < 0:
        raise ValueError("CREATE TABLE 缺少字段定义括号，无法推导当前表结构。")
    end = _find_matching_parenthesis(masked_text, start)
    if end < 0:
        raise ValueError("CREATE TABLE 括号未闭合，无法推导当前表结构。")
    body = statement_text[start + 1:end]
    columns = []
    for definition in _split_sql_csv(body):
        column_name = _parse_create_table_column_name(definition)
        if not column_name:
            continue
        columns.append(
            {
                "raw": column_name,
                "normalized": _normalize_identifier(column_name),
            }
        )
    if not columns:
        raise ValueError("CREATE TABLE 中未解析到字段定义，无法推导当前表结构。")
    return columns


def _apply_alter_table_statement(columns, statement_text, table_name):
    masked_text = _mask_sql_comments(statement_text)
    match = _ALTER_TABLE_RE.match(masked_text)
    if match is None:
        raise ValueError("ALTER TABLE 语句格式不支持自动推导，请粘贴当前建表 SQL。")
    table_expression = statement_text[match.start("table"):match.end("table")].strip()
    if _normalize_identifier(_table_leaf_name(table_expression)) != _normalize_identifier(table_name):
        raise ValueError("ALTER TABLE 中的表名与目标表名不一致。")
    clause_text = statement_text[match.end("table"):]
    updated = list(columns)
    for clause in _split_sql_csv(clause_text):
        stripped = str(clause or "").strip()
        if not stripped:
            continue
        updated = _apply_alter_clause(updated, stripped)
    return updated


def _apply_alter_clause(columns, clause_text):
    masked_clause = _mask_sql_comments(clause_text)
    upper_clause = re.sub(r"\s+", " ", masked_clause.strip()).upper()
    if not upper_clause:
        return list(columns)
    if re.match(r"^ADD\s+(PRIMARY|UNIQUE|KEY|INDEX|CONSTRAINT|FOREIGN|FULLTEXT|SPATIAL|CHECK)\b", upper_clause):
        raise ValueError("ALTER TABLE 包含不支持的索引或约束变更，请粘贴当前建表 SQL。")
    if re.match(r"^DROP\s+(PRIMARY|KEY|INDEX|CONSTRAINT|FOREIGN)\b", upper_clause):
        raise ValueError("ALTER TABLE 包含不支持的索引或约束删除，请粘贴当前建表 SQL。")
    if re.match(r"^RENAME\b", upper_clause):
        raise ValueError("ALTER TABLE 包含不支持的重命名操作，请粘贴当前建表 SQL。")

    add_match = re.match(
        r"^\s*ADD\s+(?:COLUMN\s+)?(?:IF\s+NOT\s+EXISTS\s+)?(?P<name>{})\b".format(SQL_IDENTIFIER_PATTERN),
        masked_clause,
        re.IGNORECASE | re.DOTALL,
    )
    if add_match is not None:
        raw_name = clause_text[add_match.start("name"):add_match.end("name")].strip()
        return _insert_column(
            columns,
            {"raw": raw_name, "normalized": _normalize_identifier(raw_name)},
            _parse_alter_position(clause_text, masked_clause),
        )

    drop_match = re.match(
        r"^\s*DROP\s+(?:COLUMN\s+)?(?:IF\s+EXISTS\s+)?(?P<name>{})\b".format(SQL_IDENTIFIER_PATTERN),
        masked_clause,
        re.IGNORECASE | re.DOTALL,
    )
    if drop_match is not None:
        raw_name = clause_text[drop_match.start("name"):drop_match.end("name")].strip()
        return _drop_column(columns, _normalize_identifier(raw_name))

    modify_match = re.match(
        r"^\s*MODIFY\s+(?:COLUMN\s+)?(?P<name>{})\b".format(SQL_IDENTIFIER_PATTERN),
        masked_clause,
        re.IGNORECASE | re.DOTALL,
    )
    if modify_match is not None:
        raw_name = clause_text[modify_match.start("name"):modify_match.end("name")].strip()
        return _replace_column(
            columns,
            _normalize_identifier(raw_name),
            {"raw": raw_name, "normalized": _normalize_identifier(raw_name)},
            _parse_alter_position(clause_text, masked_clause),
        )

    change_match = re.match(
        r"^\s*CHANGE\s+(?:COLUMN\s+)?(?P<old>{})\s+(?P<new>{})\b".format(
            SQL_IDENTIFIER_PATTERN,
            SQL_IDENTIFIER_PATTERN,
        ),
        masked_clause,
        re.IGNORECASE | re.DOTALL,
    )
    if change_match is not None:
        raw_old = clause_text[change_match.start("old"):change_match.end("old")].strip()
        raw_new = clause_text[change_match.start("new"):change_match.end("new")].strip()
        return _rename_column(
            columns,
            _normalize_identifier(raw_old),
            {"raw": raw_new, "normalized": _normalize_identifier(raw_new)},
            _parse_alter_position(clause_text, masked_clause),
        )

    raise ValueError("ALTER TABLE 存在不支持的子句，请粘贴当前建表 SQL。")


def _parse_alter_position(clause_text, masked_clause):
    if re.search(r"\bFIRST\s*$", masked_clause, re.IGNORECASE):
        return {"kind": "first", "after": ""}
    after_match = re.search(
        r"\bAFTER\s+(?P<name>{})\s*$".format(SQL_IDENTIFIER_PATTERN),
        masked_clause,
        re.IGNORECASE | re.DOTALL,
    )
    if after_match is None:
        return {"kind": "", "after": ""}
    raw_name = clause_text[after_match.start("name"):after_match.end("name")].strip()
    return {"kind": "after", "after": _normalize_identifier(raw_name)}


def _parse_create_table_column_name(definition):
    stripped = str(definition or "").strip()
    if not stripped:
        return ""
    upper = re.sub(r"\s+", " ", stripped).upper()
    for keyword in (
        "PRIMARY KEY",
        "UNIQUE KEY",
        "UNIQUE INDEX",
        "FULLTEXT KEY",
        "SPATIAL KEY",
        "FOREIGN KEY",
        "CONSTRAINT",
        "KEY ",
        "INDEX ",
        "CHECK ",
    ):
        if upper.startswith(keyword):
            return ""
    return _parse_leading_identifier(stripped)


def _parse_leading_identifier(text):
    stripped = str(text or "").lstrip()
    if not stripped:
        return ""
    if stripped[0] == "`":
        end = stripped.find("`", 1)
        if end < 0:
            return ""
        return stripped[: end + 1]
    match = re.match(r"[A-Za-z_][\w$]*", stripped)
    if match is None:
        return ""
    return stripped[: match.end()]


def _find_matching_parenthesis(text, start_index):
    depth = 0
    in_string = False
    index = int(start_index)
    length = len(text)
    while index < length:
        char = text[index]
        next_char = text[index + 1] if index + 1 < length else ""
        if in_string:
            if char == "'" and next_char == "'":
                index += 2
                continue
            if char == "'":
                in_string = False
            index += 1
            continue
        if char == "'":
            in_string = True
            index += 1
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return -1


def _insert_column(columns, column, position):
    normalized = column["normalized"]
    if _find_column_index(columns, normalized) >= 0:
        raise ValueError("ALTER TABLE ADD COLUMN 与现有字段重复，无法可靠推导当前表结构。")
    result = list(columns)
    return _place_column(result, column, position, fallback_index=len(result))


def _drop_column(columns, normalized_name):
    result = list(columns)
    index = _find_column_index(result, normalized_name)
    if index < 0:
        raise ValueError("ALTER TABLE DROP COLUMN 引用了不存在的字段，无法可靠推导当前表结构。")
    del result[index]
    return result


def _replace_column(columns, normalized_name, column, position):
    result = list(columns)
    index = _find_column_index(result, normalized_name)
    if index < 0:
        raise ValueError("ALTER TABLE MODIFY COLUMN 引用了不存在的字段，无法可靠推导当前表结构。")
    del result[index]
    return _place_column(result, column, position, fallback_index=index)


def _rename_column(columns, normalized_name, column, position):
    result = list(columns)
    index = _find_column_index(result, normalized_name)
    if index < 0:
        raise ValueError("ALTER TABLE CHANGE COLUMN 引用了不存在的字段，无法可靠推导当前表结构。")
    duplicate_index = _find_column_index(result, column["normalized"])
    if duplicate_index >= 0 and duplicate_index != index:
        raise ValueError("ALTER TABLE CHANGE COLUMN 生成了重复字段名，无法可靠推导当前表结构。")
    del result[index]
    return _place_column(result, column, position, fallback_index=index)


def _place_column(columns, column, position, fallback_index):
    result = list(columns)
    kind = str((position or {}).get("kind", "") or "")
    if kind == "first":
        result.insert(0, column)
        return result
    if kind == "after":
        after_name = str((position or {}).get("after", "") or "")
        after_index = _find_column_index(result, after_name)
        if after_index < 0:
            raise ValueError("ALTER TABLE 的 AFTER 字段不存在，无法可靠推导当前表结构。")
        result.insert(after_index + 1, column)
        return result
    result.insert(min(max(int(fallback_index), 0), len(result)), column)
    return result


def _find_column_index(columns, normalized_name):
    target = _normalize_identifier(normalized_name)
    for index, column in enumerate(columns):
        if _normalize_identifier(column.get("normalized", "")) == target:
            return index
    return -1


def build_sql_translation_user_prompt(
    source_path,
    line,
    table_name,
    primary_key_field,
    primary_key_value,
    source_field,
    source_text,
    target_field,
    target_text,
    target_missing,
    locked_terms,
    extra_prompt,
):
    payload = {
        "source_text": source_text,
        "target_text": target_text,
        "target_missing": bool(target_missing),
        "locked_terms": [
            {"source": term["source"], "target": term["target"]}
            for term in locked_terms
        ],
        "extra_prompt": extra_prompt or "",
    }
    sections = []
    extra_instruction = str(extra_prompt or "").strip()
    if extra_instruction:
        sections.append(
            "High-priority additional instruction from user: {}. Follow it unless it conflicts with source_text meaning, placeholders, or locked_terms.".format(
                extra_instruction
            )
        )
    sections.append("Task payload JSON:")
    sections.append(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    return "\n".join(sections)


def build_sql_translation_system_prompt():
    return (
        "You are a professional translator and reviewer for SQL seed data.\n"
        "Return JSON only with keys: verdict, candidate_translation, reason.\n"
        "verdict must be either accurate or needs_update.\n"
        "candidate_translation must contain only the translated English field text, never return SQL.\n"
        "candidate_translation must be natural English and must not directly copy the Chinese source text.\n"
        "candidate_translation must not include Chinese explanations, SQL, JSON, or multiple lines.\n"
        "reason must be written in Simplified Chinese.\n"
        "Do not output English in reason unless it is a required technical term quoted from the source or candidate text.\n"
        "Preserve placeholders exactly, including {0}, {}, %s, ${name} and similar forms.\n"
        "If locked_terms are provided, candidate_translation must use the target terms exactly as given, while sentence-initial capitalization is allowed.\n"
        "If extra_prompt is provided, treat it as a high-priority additional instruction and apply it unless it conflicts with source_text meaning, placeholders, or locked_terms.\n"
        "If target_text is already accurate, set verdict=accurate and candidate_translation to the unchanged target_text."
    )


def build_sql_translation_review_user_prompt(
    source_path,
    line,
    table_name,
    primary_key_field,
    primary_key_value,
    source_field,
    source_text,
    target_field,
    candidate_text,
    target_missing,
    locked_terms,
    extra_prompt,
):
    payload = {
        "source_text": source_text,
        "candidate_text": candidate_text,
        "target_missing": bool(target_missing),
        "locked_terms": [
            {"source": term["source"], "target": term["target"]}
            for term in locked_terms
        ],
        "extra_prompt": extra_prompt or "",
    }
    sections = []
    extra_instruction = str(extra_prompt or "").strip()
    if extra_instruction:
        sections.append(
            "High-priority additional instruction from user: {}. Review whether candidate_text follows it unless the instruction conflicts with source_text meaning, placeholders, or locked_terms.".format(
                extra_instruction
            )
        )
    sections.append("Review payload JSON:")
    sections.append(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    return "\n".join(sections)


def build_sql_translation_review_system_prompt():
    return (
        "You are a strict QA reviewer for English SQL seed translations.\n"
        "Return JSON only with keys: decision, issues.\n"
        "decision must be either pass or fail.\n"
        "issues must be either an array of short Simplified Chinese strings or an array of objects with keys code, message, severity, evidence, and expected_term.\n"
        "For object issues, message and evidence must be written in Simplified Chinese. expected_term may contain English terminology.\n"
        "Ignore any previous English wording. Review candidate_text on its own merits against source_text.\n"
        "Judge candidate_text against source_text, placeholders, locked_terms, and extra_prompt when extra_prompt is provided.\n"
        "Do not fail solely because a locked term uses different capitalization. Treat locked_terms matching as case-insensitive.\n"
        "Do not report that a term should be X if candidate_text already contains X.\n"
        "Do not treat style-only suggestions such as 'could be more natural' as hard failures.\n"
        "extra_prompt is a high-priority additional instruction unless it conflicts with source_text meaning, placeholders, or locked_terms.\n"
        "Do not output English in message or evidence unless it is a required technical term quoted from source_text, candidate_text, or locked_terms.\n"
        "Only report spelling or wording problems that actually appear in candidate_text.\n"
        "Fail when the candidate is not natural English, still contains untranslated Chinese, omits source meaning, or breaks placeholders.\n"
        "Pass only when the candidate is a complete and accurate English translation of the source text."
    )


def _build_update_sql(item):
    return "UPDATE {table} SET {target_field} = '{value}' WHERE {primary_key_field} = {primary_key};".format(
        table=item.get("table_expression", ""),
        target_field=item.get("target_field_sql", ""),
        value=_escape_sql_string(item.get("candidate_text", "")),
        primary_key_field=item.get("primary_key_field_sql", ""),
        primary_key=item.get("primary_key_literal", ""),
    )


def _build_scan_event(path, line, reason, statement_text="", parse_phase=""):
    return {
        "at": _timestamp(),
        "label": "已跳过",
        "source_path": str(path),
        "line": int(line),
        "primary_key_value": "",
        "source_text": "",
        "target_text": reason,
        "reason": str(reason or ""),
        "parse_phase": str(parse_phase or ""),
        "statement_preview": _preview_sql_statement(statement_text),
    }


def _build_info_event(path, line, label, detail, parse_phase=""):
    return {
        "at": _timestamp(),
        "label": str(label or ""),
        "source_path": str(path or ""),
        "line": int(line or 0),
        "primary_key_value": "",
        "source_text": "",
        "target_text": "",
        "reason": str(detail or ""),
        "parse_phase": str(parse_phase or ""),
        "statement_preview": "",
    }


def _load_written_item_ids(path):
    text = Path(path).read_text(encoding="utf-8")
    written = set()
    for line in text.splitlines():
        if line.startswith("-- item:"):
            written.add(line[len("-- item:"):].strip())
    return written


def _preview_sql_statement(text, limit=1200):
    value = str(text or "").strip()
    if not value:
        return ""
    lines = [line.rstrip() for line in value.splitlines()]
    preview = "\n".join(lines).strip()
    if len(preview) <= limit:
        return preview
    return preview[: max(limit - 3, 0)].rstrip() + "..."


def _mask_sql_comments(text):
    chars = []
    index = 0
    length = len(text)
    in_string = False
    in_line_comment = False
    in_block_comment = False
    while index < length:
        char = text[index]
        next_char = text[index + 1] if index + 1 < length else ""
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
                chars.append(char)
            else:
                chars.append(" ")
            index += 1
            continue
        if in_block_comment:
            if char == "*" and next_char == "/":
                chars.append(" ")
                chars.append(" ")
                index += 2
                in_block_comment = False
                continue
            if char == "\n":
                chars.append(char)
            else:
                chars.append(" ")
            index += 1
            continue
        if in_string:
            chars.append(char)
            if char == "'" and next_char == "'":
                chars.append(next_char)
                index += 2
                continue
            if char == "'":
                in_string = False
            index += 1
            continue
        if char == "'" and not in_string:
            in_string = True
            chars.append(char)
            index += 1
            continue
        if char == "-" and next_char == "-":
            in_line_comment = True
            chars.append(" ")
            chars.append(" ")
            index += 2
            continue
        if char == "#":
            in_line_comment = True
            chars.append(" ")
            index += 1
            continue
        if char == "/" and next_char == "*":
            in_block_comment = True
            chars.append(" ")
            chars.append(" ")
            index += 2
            continue
        chars.append(char)
        index += 1
    return "".join(chars)


def _split_sql_statements(text, masked_text):
    statements = []
    start_index = None
    start_line = 1
    line = 1
    in_string = False
    index = 0
    length = len(masked_text)
    while index < length:
        char = masked_text[index]
        next_char = masked_text[index + 1] if index + 1 < length else ""
        if start_index is None and not char.isspace():
            start_index = index
            start_line = line
        if in_string:
            if char == "'" and next_char == "'":
                index += 2
                continue
            if char == "'":
                in_string = False
        else:
            if char == "'":
                in_string = True
            elif char == ";":
                if start_index is not None:
                    statements.append(
                        {
                            "text": text[start_index:index],
                            "masked_text": masked_text[start_index:index],
                            "line": start_line,
                        }
                    )
                    start_index = None
        if char == "\n":
            line += 1
        index += 1
    if start_index is not None:
        statements.append(
            {
                "text": text[start_index:],
                "masked_text": masked_text[start_index:],
                "line": start_line,
            }
        )
    return statements


def _parse_identifier_list(columns_text):
    inner = str(columns_text or "").strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]
    parts = _split_simple_csv(inner)
    result = []
    for part in parts:
        raw = part.strip()
        if not raw:
            continue
        result.append(
            {
                "raw": raw,
                "normalized": _normalize_identifier(raw),
            }
        )
    return result


def _parse_values_groups(values_text, base_line):
    groups = []
    in_string = False
    depth = 0
    start = None
    line = base_line
    group_line = base_line
    index = 0
    length = len(values_text)
    while index < length:
        char = values_text[index]
        next_char = values_text[index + 1] if index + 1 < length else ""
        if in_string:
            if char == "'" and next_char == "'":
                index += 2
                continue
            if char == "'":
                in_string = False
        else:
            if char == "'":
                in_string = True
            elif char == "(":
                if depth == 0:
                    start = index
                    group_line = line
                depth += 1
            elif char == ")":
                if depth > 0:
                    depth -= 1
                    if depth == 0 and start is not None:
                        groups.append(
                            {
                                "text": values_text[start:index + 1],
                                "line": group_line,
                            }
                        )
                        start = None
        if char == "\n":
            line += 1
        index += 1
    return groups


def _split_tuple_values(group_text):
    inner = str(group_text or "").strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]
    return _split_sql_csv(inner)


def _split_simple_csv(text):
    parts = []
    token = []
    in_backtick = False
    for char in text:
        if char == "`":
            in_backtick = not in_backtick
            token.append(char)
            continue
        if char == "," and not in_backtick:
            parts.append("".join(token))
            token = []
            continue
        token.append(char)
    parts.append("".join(token))
    return parts


def _sql_row_precedence_key(row):
    source_path = Path(str(row.get("source_path", "") or ""))
    file_name_key = _natural_sort_key(source_path.name)
    full_path_key = _natural_sort_key(str(source_path))
    line = int(row.get("line", 0) or 0)
    return (file_name_key, full_path_key, line)


def _natural_sort_key(value):
    parts = re.findall(r"\d+|[A-Za-z]+|[^A-Za-z\d]+", str(value or ""))
    key = []
    for part in parts:
        if part.isdigit():
            key.append((0, int(part)))
        else:
            key.append((1, part.lower()))
    return tuple(key)


def _split_sql_csv(text):
    parts = []
    token = []
    in_string = False
    depth = 0
    index = 0
    length = len(text)
    while index < length:
        char = text[index]
        next_char = text[index + 1] if index + 1 < length else ""
        if in_string:
            token.append(char)
            if char == "'" and next_char == "'":
                token.append(next_char)
                index += 2
                continue
            if char == "'":
                in_string = False
            index += 1
            continue
        if char == "'":
            in_string = True
            token.append(char)
            index += 1
            continue
        if char == "(":
            depth += 1
            token.append(char)
            index += 1
            continue
        if char == ")":
            if depth > 0:
                depth -= 1
            token.append(char)
            index += 1
            continue
        if char == "," and depth == 0:
            parts.append("".join(token))
            token = []
            index += 1
            continue
        token.append(char)
        index += 1
    parts.append("".join(token))
    return parts


def _normalize_identifier(value):
    text = str(value or "").strip()
    if text.startswith("`") and text.endswith("`"):
        text = text[1:-1]
    return text.replace("`", "").replace(" ", "").lower()


def _table_leaf_name(table_expression):
    text = str(table_expression or "").strip()
    if "." not in text:
        return text
    return text.split(".")[-1]


def _sql_value_to_text(token):
    value = str(token or "").strip()
    if not value:
        return ""
    if value.upper() == "NULL":
        return ""
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def _sql_value_to_display(token):
    value = str(token or "").strip()
    if not value:
        return ""
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def _escape_sql_string(value):
    return str(value or "").replace("'", "''")


def _safe_file_name_component(value):
    chars = []
    for char in str(value or ""):
        if char.isalnum() or char in ("-", "_"):
            chars.append(char)
        else:
            chars.append("_")
    result = "".join(chars).strip("_")
    return result or "table"

def _timestamp():
    return datetime.now().astimezone().replace(microsecond=0).isoformat()


def _display_text(value):
    return decode_unicode_escapes(str(value or ""))


def _normalize_reason(reason, fallback):
    value = _display_text(reason).strip()
    if is_chinese_explanation_text(value):
        return value
    return str(fallback or "").strip()


def _saved_sql_session_uses_obsolete_duplicate_reason(payload):
    old_reason = "定位字段值重复，无法唯一定位 update。"
    if not isinstance(payload, dict):
        return False
    for row in payload.get("rows", []):
        if str((row or {}).get("skip_reason", "") or "") == old_reason:
            return True
    for event in payload.get("events", []):
        if str((event or {}).get("reason", "") or "") == old_reason:
            return True
    return False
