from __future__ import absolute_import

import json
import re
import threading
from collections import OrderedDict
from datetime import datetime
from pathlib import Path

from zh_audit.terminology_xlsx import exact_terminology_translation, match_locked_terms


SQL_TRANSLATION_SESSION_VERSION = 1
SQL_TRANSLATION_OUTPUT_PREFIX = "-- Generated by zh-audit SQL校译"


def default_sql_translation_config():
    return {
        "directory_path": "",
        "table_name": "",
        "primary_key_field": "id",
        "source_field": "",
        "target_field": "",
    }


class SqlTranslationSession(object):
    def __init__(
        self,
        directory_path,
        table_name,
        primary_key_field,
        source_field,
        target_field,
        glossary,
        model_config,
        model_runner,
        persist_callback=None,
        rows=None,
        scan_events=None,
    ):
        self.lock = threading.RLock()
        self.directory_path = str(directory_path)
        self.table_name = str(table_name)
        self.primary_key_field = str(primary_key_field)
        self.source_field = str(source_field)
        self.target_field = str(target_field)
        self.glossary = OrderedDict(glossary)
        self.model_config = dict(model_config)
        self.model_runner = model_runner
        self.persist_callback = persist_callback
        if rows is None:
            discovered = scan_sql_translation_directory(
                directory_path=directory_path,
                table_name=table_name,
                primary_key_field=primary_key_field,
                source_field=source_field,
                target_field=target_field,
            )
            rows = discovered["rows"]
            scan_events = discovered["events"]
        self.rows = list(rows or [])
        self.items = OrderedDict()
        self.pending_ids = []
        self.recent_ids = []
        self.events = list(scan_events or [])
        self.total = len(self.rows)
        self.processed = 0
        self.skipped = 0
        self.pending = 0
        self.accepted = 0
        self.appended = 0
        self.failed = 0
        self.rejected = 0
        self.regenerated = 0
        self.glossary_applied = 0
        self.current = {
            "file_path": "",
            "primary_key_value": "",
            "source_text": "",
            "status": "",
        }
        self.status = "idle"
        self.message = "等待校译"
        self.error = ""
        self.started_at = ""
        self.finished_at = ""
        self.stop_requested = False
        self.next_id = 1
        self.next_index = 0
        self.output_path = ""
        self.written_item_ids = set()

    @classmethod
    def from_saved_state(cls, payload, glossary, model_config, model_runner, persist_callback=None):
        session = cls(
            directory_path=str(payload.get("directory_path", "") or ""),
            table_name=str(payload.get("table_name", "") or ""),
            primary_key_field=str(payload.get("primary_key_field", "") or ""),
            source_field=str(payload.get("source_field", "") or ""),
            target_field=str(payload.get("target_field", "") or ""),
            glossary=glossary,
            model_config=model_config,
            model_runner=model_runner,
            persist_callback=persist_callback,
            rows=list(payload.get("rows", [])),
            scan_events=[],
        )
        session._restore_saved_state(payload)
        return session

    def start(self):
        with self.lock:
            self.status = "running"
            self.message = "校译中"
            self.error = ""
            self.started_at = _timestamp()
            self.finished_at = ""
            self.stop_requested = False
            self.next_index = 0
            self.output_path = self._build_output_path()
            self._initialize_output_file()
            self._persist_locked()

    def stop(self):
        with self.lock:
            self.stop_requested = True
            if self.status == "running":
                self.message = "停止中"
            self._persist_locked()

    def resume(self):
        with self.lock:
            if not self.can_resume():
                raise ValueError("SQL translation task cannot be resumed.")
            output_path = Path(self.output_path)
            if not output_path.exists():
                raise ValueError("SQL output file does not exist: {}".format(output_path))
            self.written_item_ids = _load_written_item_ids(output_path)
            self.status = "running"
            self.message = "校译中"
            self.error = ""
            self.finished_at = ""
            self.stop_requested = False
            if self.current.get("file_path"):
                self.current["status"] = "处理中"
            self._persist_locked()

    def can_resume(self):
        return self.status in ("interrupted", "stopped") and self.next_index < self.total

    def mark_restarted(self):
        with self.lock:
            if self.status == "running":
                self.status = "interrupted"
                self.message = "服务重启，可从上次位置继续"
                self.error = ""
                self.finished_at = _timestamp()
                if self.current.get("file_path"):
                    self.current["status"] = "等待继续"
                self.stop_requested = False
                self._persist_locked()

    def interrupt(self, error_message):
        with self.lock:
            self.status = "interrupted"
            self.message = "校译中断"
            self.error = str(error_message)
            self.finished_at = _timestamp()
            self.stop_requested = False
            if self.current.get("file_path"):
                self.current["status"] = "等待继续"
            self._persist_locked()

    def snapshot(self):
        with self.lock:
            pending_items = [self._public_item(self.items[item_id]) for item_id in self.pending_ids]
            recent_items = [self._public_item(self.items[item_id]) for item_id in self.recent_ids]
            return {
                "config": {
                    "directory_path": self.directory_path,
                    "table_name": self.table_name,
                    "primary_key_field": self.primary_key_field,
                    "source_field": self.source_field,
                    "target_field": self.target_field,
                },
                "status": {
                    "status": self.status,
                    "message": self.message,
                    "error": self.error,
                    "started_at": self.started_at,
                    "finished_at": self.finished_at,
                    "output_path": self.output_path,
                    "current": dict(self.current),
                    "counts": self._counts_payload(),
                },
                "pending_items": pending_items,
                "recent_items": recent_items,
                "events": list(self.events),
            }

    def save_state(self):
        with self.lock:
            return self._saved_state_locked()

    def run(self):
        while True:
            with self.lock:
                if self.stop_requested:
                    self.status = "stopped"
                    self.message = "已停止"
                    self.finished_at = _timestamp()
                    self.current = {
                        "file_path": "",
                        "primary_key_value": "",
                        "source_text": "",
                        "status": "",
                    }
                    self._persist_locked()
                    return
                if self.next_index >= self.total:
                    if self.status == "running":
                        self.status = "done"
                        self.message = "校译完成"
                        self.finished_at = _timestamp()
                        self.current = {
                            "file_path": "",
                            "primary_key_value": "",
                            "source_text": "",
                            "status": "",
                        }
                        self._persist_locked()
                    return
                row = self.rows[self.next_index]
                self.current = {
                    "file_path": row.get("source_path", ""),
                    "primary_key_value": row.get("primary_key_display", ""),
                    "source_text": row.get("source_text", ""),
                    "status": "处理中",
                }
                self._persist_locked()

            self._process_row(row)

            with self.lock:
                self.next_index += 1
                self.current = {
                    "file_path": row.get("source_path", ""),
                    "primary_key_value": row.get("primary_key_display", ""),
                    "source_text": row.get("source_text", ""),
                    "status": "已处理",
                }
                self._persist_locked()

    def accept(self, item_id):
        with self.lock:
            item = self._require_pending_item(item_id)
            appended = self._append_update_sql_once(item)
            item["status"] = "accepted"
            item["target_text"] = item.get("candidate_text", "")
            item["updated_at"] = _timestamp()
            item["accepted_reason"] = "人工接收"
            self.pending_ids.remove(item_id)
            self.pending -= 1
            self.accepted += 1
            if appended:
                self.appended += 1
            self._push_recent(item_id)
            self._push_event("人工接收", item, item.get("candidate_text", ""))
            self._persist_locked()
            return self.snapshot()

    def reject(self, item_id):
        with self.lock:
            item = self._require_pending_item(item_id)
            item["status"] = "rejected"
            item["updated_at"] = _timestamp()
            self.pending_ids.remove(item_id)
            self.pending -= 1
            self.rejected += 1
            self._push_recent(item_id)
            self._push_event("已忽略", item, item.get("candidate_text", ""))
            self._persist_locked()
            return self.snapshot()

    def regenerate(self, item_id, extra_prompt):
        with self.lock:
            item = self._require_pending_item(item_id)
            item["status"] = "regenerating"
            item["updated_at"] = _timestamp()
            self._persist_locked()
            source_text = item.get("source_text", "")
            target_text = item.get("target_text", "")
            locked_terms = list(item.get("locked_terms", []))
        result = self.model_runner(
            source_path=item.get("source_path", ""),
            line=item.get("line", 0),
            table_name=item.get("table_name", self.table_name),
            primary_key_field=item.get("primary_key_field", self.primary_key_field),
            primary_key_value=item.get("primary_key_display", ""),
            source_field=item.get("source_field", self.source_field),
            source_text=source_text,
            target_field=item.get("target_field", self.target_field),
            target_text=target_text,
            target_missing=item.get("target_missing", False),
            locked_terms=locked_terms,
            model_config=self.model_config,
            extra_prompt=extra_prompt,
        )
        normalized = self._normalize_model_result(item, result, target_text)
        with self.lock:
            item["candidate_text"] = normalized["candidate_text"]
            item["reason"] = normalized["reason"]
            item["verdict"] = normalized["verdict"]
            item["status"] = "pending"
            item["updated_at"] = _timestamp()
            item["regeneration_prompt"] = extra_prompt
            self.regenerated += 1
            self._push_event("已重生成", item, item.get("candidate_text", ""))
            self._persist_locked()
            return self.snapshot()

    def _process_row(self, row):
        skip_reason = str(row.get("skip_reason", "") or "")
        if skip_reason:
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, skip_reason)
                self._persist_locked()
            return

        source_text = str(row.get("source_text", "") or "")
        target_text = str(row.get("target_text", "") or "")
        if not source_text.strip():
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, "中文文案为空。")
                self._persist_locked()
            return

        exact_translation = exact_terminology_translation(source_text, self.glossary)
        locked_terms = match_locked_terms(source_text, self.glossary)
        if exact_translation:
            if target_text.strip() == exact_translation.strip():
                with self.lock:
                    self.processed += 1
                    self.skipped += 1
                    self.glossary_applied += 1
                    self._push_event("术语已准确", row, target_text)
                    self._persist_locked()
                return
            item = self._create_item(
                row=row,
                target_text=target_text,
                candidate_text=exact_translation,
                locked_terms=locked_terms,
                reason="整句命中术语词典。",
                verdict="needs_update",
                target_missing=not target_text.strip(),
            )
            with self.lock:
                self.glossary_applied += 1
                self._finalize_item(item, "术语命中")
            return

        result = self.model_runner(
            source_path=row.get("source_path", ""),
            line=row.get("line", 0),
            table_name=row.get("table_name", self.table_name),
            primary_key_field=row.get("primary_key_field", self.primary_key_field),
            primary_key_value=row.get("primary_key_display", ""),
            source_field=row.get("source_field", self.source_field),
            source_text=source_text,
            target_field=row.get("target_field", self.target_field),
            target_text=target_text,
            target_missing=not target_text.strip(),
            locked_terms=locked_terms,
            model_config=self.model_config,
            extra_prompt="",
        )
        normalized = self._normalize_model_result(
            {
                "source_path": row.get("source_path", ""),
                "line": row.get("line", 0),
                "table_name": row.get("table_name", self.table_name),
                "primary_key_field": row.get("primary_key_field", self.primary_key_field),
                "primary_key_display": row.get("primary_key_display", ""),
                "source_field": row.get("source_field", self.source_field),
                "source_text": source_text,
                "target_field": row.get("target_field", self.target_field),
                "target_text": target_text,
                "target_missing": not target_text.strip(),
                "locked_terms": locked_terms,
            },
            result,
            target_text,
        )
        if normalized["verdict"] == "accurate" and target_text.strip():
            with self.lock:
                self.processed += 1
                self.skipped += 1
                self._push_event("已跳过", row, target_text)
                self._persist_locked()
            return
        item = self._create_item(
            row=row,
            target_text=target_text,
            candidate_text=normalized["candidate_text"],
            locked_terms=locked_terms,
            reason=normalized["reason"],
            verdict=normalized["verdict"],
            target_missing=not target_text.strip(),
        )
        with self.lock:
            self._finalize_item(item, "待审批")

    def _normalize_model_result(self, item, result, current_target):
        verdict = str(result.get("verdict", "") or "").strip().lower()
        candidate = str(result.get("candidate_translation", "") or "").strip()
        reason = str(result.get("reason", "") or "").strip()
        if verdict not in ("accurate", "needs_update"):
            verdict = "needs_update"
        locked_terms = list(item.get("locked_terms", []))
        target_missing = bool(item.get("target_missing", not str(current_target or "").strip()))
        if verdict == "accurate" and target_missing:
            verdict = "needs_update"
        if verdict == "accurate":
            if locked_terms and not _contains_locked_terms(current_target, locked_terms):
                verdict = "needs_update"
                reason = "现有英文未满足术语词典要求。"
            return {
                "verdict": verdict,
                "candidate_text": current_target,
                "reason": reason or "现有英文准确。",
            }
        if not candidate:
            raise ValueError(
                "Model did not return candidate_translation for SQL item {}".format(item.get("primary_key_display", ""))
            )
        if locked_terms and not _contains_locked_terms(candidate, locked_terms):
            retry_prompt = "候选英文必须严格包含这些术语：{}。请只返回符合要求的英文。".format(
                ", ".join("{}={}".format(term["source"], term["target"]) for term in locked_terms)
            )
            retried = self.model_runner(
                source_path=item.get("source_path", ""),
                line=item.get("line", 0),
                table_name=item.get("table_name", self.table_name),
                primary_key_field=item.get("primary_key_field", self.primary_key_field),
                primary_key_value=item.get("primary_key_display", ""),
                source_field=item.get("source_field", self.source_field),
                source_text=item.get("source_text", ""),
                target_field=item.get("target_field", self.target_field),
                target_text=current_target,
                target_missing=target_missing,
                locked_terms=locked_terms,
                model_config=self.model_config,
                extra_prompt=retry_prompt,
            )
            retry_candidate = str(retried.get("candidate_translation", "") or "").strip()
            retry_reason = str(retried.get("reason", "") or "").strip()
            if retry_candidate and _contains_locked_terms(retry_candidate, locked_terms):
                return {
                    "verdict": "needs_update",
                    "candidate_text": retry_candidate,
                    "reason": retry_reason or "按术语词典重试后生成。",
                }
            return {
                "verdict": "needs_update",
                "candidate_text": retry_candidate or candidate,
                "reason": "术语不符合：{}".format(
                    ", ".join("{}={}".format(term["source"], term["target"]) for term in locked_terms)
                ),
            }
        return {
            "verdict": "needs_update",
            "candidate_text": candidate,
            "reason": reason or "模型建议更新英文翻译。",
        }

    def _create_item(self, row, target_text, candidate_text, locked_terms, reason, verdict, target_missing):
        with self.lock:
            item_id = "sql-{}".format(self.next_id)
            self.next_id += 1
            item = {
                "id": item_id,
                "source_path": row.get("source_path", ""),
                "line": int(row.get("line", 0) or 0),
                "table_expression": row.get("table_expression", ""),
                "table_name": row.get("table_name", self.table_name),
                "primary_key_field_sql": row.get("primary_key_field_sql", self.primary_key_field),
                "primary_key_field": row.get("primary_key_field", self.primary_key_field),
                "primary_key_literal": row.get("primary_key_literal", ""),
                "primary_key_display": row.get("primary_key_display", ""),
                "source_field": row.get("source_field", self.source_field),
                "source_text": row.get("source_text", ""),
                "target_field_sql": row.get("target_field_sql", self.target_field),
                "target_field": row.get("target_field", self.target_field),
                "target_text": target_text,
                "candidate_text": candidate_text,
                "locked_terms": [dict(term) for term in locked_terms],
                "reason": reason,
                "verdict": verdict,
                "target_missing": bool(target_missing),
                "status": "pending",
                "updated_at": _timestamp(),
            }
            self.items[item_id] = item
            self._persist_locked()
            return item

    def _finalize_item(self, item, event_label):
        self.processed += 1
        item["status"] = "pending"
        item["updated_at"] = _timestamp()
        self.pending_ids.append(item["id"])
        self.pending += 1
        self._push_event(event_label, item, item.get("candidate_text", ""))
        self._persist_locked()

    def _append_update_sql_once(self, item):
        item_id = item["id"]
        if item_id in self.written_item_ids:
            return False
        output_path = Path(self.output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        rendered = "\n".join(
            [
                "-- item:{}".format(item_id),
                "-- source:{}:{}".format(item.get("source_path", ""), item.get("line", 0)),
                _build_update_sql(item),
                "",
            ]
        )
        with output_path.open("a", encoding="utf-8") as handle:
            handle.write(rendered)
        self.written_item_ids.add(item_id)
        return True

    def _initialize_output_file(self):
        output_path = Path(self.output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        header = "\n".join(
            [
                SQL_TRANSLATION_OUTPUT_PREFIX,
                "-- table: {}".format(self.table_name),
                "-- primary_key_field: {}".format(self.primary_key_field),
                "-- source_field: {}".format(self.source_field),
                "-- target_field: {}".format(self.target_field),
                "-- source_directory: {}".format(self.directory_path),
                "-- created_at: {}".format(_timestamp()),
                "",
            ]
        )
        output_path.write_text(header, encoding="utf-8")
        self.written_item_ids = set()

    def _build_output_path(self):
        directory = Path(self.directory_path)
        safe_table = _safe_file_name_component(self.table_name or "table")
        file_name = "{}_sql_audit_{}.sql".format(safe_table, datetime.now().strftime("%Y%m%d_%H%M%S"))
        return str((directory / file_name).resolve())

    def _push_recent(self, item_id):
        if item_id in self.recent_ids:
            self.recent_ids.remove(item_id)
        self.recent_ids.insert(0, item_id)
        del self.recent_ids[50:]

    def _push_event(self, label, item, detail):
        self.events.insert(
            0,
            {
                "at": _timestamp(),
                "label": label,
                "source_path": item.get("source_path", ""),
                "line": item.get("line", 0),
                "primary_key_value": item.get("primary_key_display", ""),
                "source_text": item.get("source_text", ""),
                "target_text": detail,
            },
        )
        del self.events[100:]

    def _public_item(self, item):
        return {
            "id": item["id"],
            "source_path": item.get("source_path", ""),
            "line": item.get("line", 0),
            "primary_key_value": item.get("primary_key_display", ""),
            "source_text": item.get("source_text", ""),
            "target_text": item.get("target_text", ""),
            "candidate_text": item.get("candidate_text", ""),
            "locked_terms": [dict(term) for term in item.get("locked_terms", [])],
            "reason": item.get("reason", ""),
            "verdict": item.get("verdict", ""),
            "status": item.get("status", ""),
            "updated_at": item.get("updated_at", ""),
        }

    def _require_pending_item(self, item_id):
        item = self.items.get(item_id)
        if item is None:
            raise KeyError("Unknown SQL translation item: {}".format(item_id))
        if item.get("status") != "pending":
            raise ValueError("SQL translation item is not pending: {}".format(item_id))
        return item

    def _counts_payload(self):
        return {
            "total": self.total,
            "processed": self.processed,
            "skipped": self.skipped,
            "pending": self.pending,
            "accepted": self.accepted,
            "appended": self.appended,
            "failed": self.failed,
            "rejected": self.rejected,
            "regenerated": self.regenerated,
            "glossary_applied": self.glossary_applied,
        }

    def _saved_state_locked(self):
        return {
            "version": SQL_TRANSLATION_SESSION_VERSION,
            "directory_path": self.directory_path,
            "table_name": self.table_name,
            "primary_key_field": self.primary_key_field,
            "source_field": self.source_field,
            "target_field": self.target_field,
            "rows": list(self.rows),
            "counts": self._counts_payload(),
            "items": [dict(item) for item in self.items.values()],
            "pending_ids": list(self.pending_ids),
            "recent_ids": list(self.recent_ids),
            "events": list(self.events),
            "current": dict(self.current),
            "status": self.status,
            "message": self.message,
            "error": self.error,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "stop_requested": bool(self.stop_requested),
            "next_id": self.next_id,
            "next_index": self.next_index,
            "output_path": self.output_path,
            "written_item_ids": sorted(self.written_item_ids),
        }

    def _restore_saved_state(self, payload):
        counts = dict(payload.get("counts", {}))
        self.rows = list(payload.get("rows", self.rows))
        self.total = len(self.rows)
        self.items = OrderedDict()
        for item in payload.get("items", []):
            item_id = str(item.get("id", "") or "")
            if not item_id:
                continue
            restored = dict(item)
            restored["id"] = item_id
            self.items[item_id] = restored
        self.pending_ids = [item_id for item_id in payload.get("pending_ids", []) if item_id in self.items]
        self.recent_ids = [item_id for item_id in payload.get("recent_ids", []) if item_id in self.items]
        self.events = list(payload.get("events", []))
        self.processed = int(counts.get("processed", 0))
        self.skipped = int(counts.get("skipped", 0))
        self.pending = int(counts.get("pending", len(self.pending_ids)))
        self.accepted = int(counts.get("accepted", 0))
        self.appended = int(counts.get("appended", 0))
        self.failed = int(counts.get("failed", 0))
        self.rejected = int(counts.get("rejected", 0))
        self.regenerated = int(counts.get("regenerated", 0))
        self.glossary_applied = int(counts.get("glossary_applied", 0))
        self.current = dict(payload.get("current", {}))
        self.status = str(payload.get("status", "idle") or "idle")
        self.message = str(payload.get("message", "等待校译") or "等待校译")
        self.error = str(payload.get("error", "") or "")
        self.started_at = str(payload.get("started_at", "") or "")
        self.finished_at = str(payload.get("finished_at", "") or "")
        self.stop_requested = bool(payload.get("stop_requested", False))
        self.next_id = max(int(payload.get("next_id", 1)), 1)
        try:
            next_index = int(payload.get("next_index", self.processed))
        except (TypeError, ValueError):
            next_index = self.processed
        self.next_index = min(max(next_index, 0), self.total)
        self.output_path = str(payload.get("output_path", "") or "")
        self.written_item_ids = set(payload.get("written_item_ids", []))
        if self.output_path:
            output_path = Path(self.output_path)
            if output_path.exists():
                self.written_item_ids = _load_written_item_ids(output_path)
        if self.status == "running":
            self.status = "interrupted"
            self.message = "服务重启，可从上次位置继续"
            self.error = ""
            self.finished_at = _timestamp()
            if self.current.get("file_path"):
                self.current["status"] = "等待继续"
            self.stop_requested = False

    def _persist_locked(self):
        if self.persist_callback is None:
            return
        self.persist_callback(self._saved_state_locked())


def scan_sql_translation_directory(directory_path, table_name, primary_key_field, source_field, target_field):
    directory = Path(directory_path).expanduser()
    rows = []
    events = []
    for path in sorted(directory.rglob("*.sql")):
        parsed = parse_sql_translation_file(
            path=path,
            table_name=table_name,
            primary_key_field=primary_key_field,
            source_field=source_field,
            target_field=target_field,
        )
        rows.extend(parsed["rows"])
        events.extend(parsed["events"])
    duplicates = {}
    for row in rows:
        key = row.get("primary_key_literal", "")
        if not key or row.get("skip_reason"):
            continue
        duplicates.setdefault(key, []).append(row)
    for duplicate_rows in duplicates.values():
        if len(duplicate_rows) < 2:
            continue
        for row in duplicate_rows:
            row["skip_reason"] = "主键值重复，无法唯一定位 update。"
    return {
        "rows": rows,
        "events": events,
    }


def parse_sql_translation_file(path, table_name, primary_key_field, source_field, target_field):
    sql_path = Path(path)
    text = sql_path.read_text(encoding="utf-8")
    masked = _mask_sql_comments(text)
    statements = _split_sql_statements(text, masked)
    rows = []
    events = []
    target_table_name = _normalize_identifier(table_name)
    target_primary = _normalize_identifier(primary_key_field)
    target_source = _normalize_identifier(source_field)
    target_target = _normalize_identifier(target_field)
    insert_table_re = re.compile(
        r"^\s*(insert|replace)\s+into\s+(?P<table>(?:`[^`]+`|[A-Za-z_][\w$]*)(?:\s*\.\s*(?:`[^`]+`|[A-Za-z_][\w$]*))?)",
        re.IGNORECASE | re.DOTALL,
    )
    insert_values_re = re.compile(
        r"^\s*insert\s+into\s+(?P<table>(?:`[^`]+`|[A-Za-z_][\w$]*)(?:\s*\.\s*(?:`[^`]+`|[A-Za-z_][\w$]*))?)\s*(?P<columns>\([^)]*\))?\s*values\b(?P<values>.*)$",
        re.IGNORECASE | re.DOTALL,
    )
    for statement in statements:
        original = statement["text"]
        masked_text = statement["masked_text"]
        table_match = insert_table_re.match(masked_text)
        if table_match is None:
            continue
        table_expression = original[table_match.start("table"):table_match.end("table")].strip()
        if _normalize_identifier(_table_leaf_name(table_expression)) != target_table_name:
            continue
        if str(table_match.group(1) or "").strip().lower() == "replace":
            events.append(_build_scan_event(sql_path, statement["line"], "REPLACE INTO 暂不支持。"))
            continue
        values_match = insert_values_re.match(masked_text)
        if values_match is None:
            events.append(_build_scan_event(sql_path, statement["line"], "仅支持 INSERT ... VALUES 语句。"))
            continue
        if values_match.group("columns") is None:
            events.append(_build_scan_event(sql_path, statement["line"], "未显式声明列名，暂不支持。"))
            continue
        columns_text = original[values_match.start("columns"):values_match.end("columns")]
        columns = _parse_identifier_list(columns_text)
        column_map = {}
        for column in columns:
            column_map[column["normalized"]] = column["raw"]
        if target_primary not in column_map:
            events.append(_build_scan_event(sql_path, statement["line"], "INSERT 语句缺少主键字段。"))
            continue
        if target_source not in column_map:
            events.append(_build_scan_event(sql_path, statement["line"], "INSERT 语句缺少中文文案字段。"))
            continue
        if target_target not in column_map:
            events.append(_build_scan_event(sql_path, statement["line"], "INSERT 语句缺少英文文案字段。"))
            continue
        values_text = original[values_match.start("values"):values_match.end("values")]
        values_line = statement["line"] + original[:values_match.start("values")].count("\n")
        groups = _parse_values_groups(values_text, values_line)
        if not groups:
            events.append(_build_scan_event(sql_path, statement["line"], "未解析到 VALUES 元组。"))
            continue
        for group in groups:
            tokens = _split_tuple_values(group["text"])
            if len(tokens) != len(columns):
                rows.append(
                    {
                        "source_path": str(sql_path),
                        "line": group["line"],
                        "table_expression": table_expression,
                        "table_name": table_name,
                        "primary_key_field": primary_key_field,
                        "primary_key_field_sql": column_map[target_primary],
                        "primary_key_literal": "",
                        "primary_key_display": "",
                        "source_field": source_field,
                        "source_text": "",
                        "target_field": target_field,
                        "target_field_sql": column_map[target_target],
                        "target_text": "",
                        "skip_reason": "VALUES 元组字段数与列数不一致。",
                    }
                )
                continue
            resolved = {}
            for index, column in enumerate(columns):
                resolved[column["normalized"]] = tokens[index].strip()
            primary_key_literal = resolved.get(target_primary, "")
            source_token = resolved.get(target_source, "")
            target_token = resolved.get(target_target, "")
            rows.append(
                {
                    "source_path": str(sql_path),
                    "line": group["line"],
                    "table_expression": table_expression,
                    "table_name": table_name,
                    "primary_key_field": primary_key_field,
                    "primary_key_field_sql": column_map[target_primary],
                    "primary_key_literal": primary_key_literal,
                    "primary_key_display": _sql_value_to_display(primary_key_literal),
                    "source_field": source_field,
                    "source_text": _sql_value_to_text(source_token),
                    "target_field": target_field,
                    "target_field_sql": column_map[target_target],
                    "target_text": _sql_value_to_text(target_token),
                    "skip_reason": "",
                }
            )
    return {
        "rows": rows,
        "events": events,
    }


def build_sql_translation_user_prompt(
    source_path,
    line,
    table_name,
    primary_key_field,
    primary_key_value,
    source_field,
    source_text,
    target_field,
    target_text,
    target_missing,
    locked_terms,
    extra_prompt,
):
    payload = {
        "source_path": source_path,
        "line": line,
        "table_name": table_name,
        "primary_key_field": primary_key_field,
        "primary_key_value": primary_key_value,
        "source_field": source_field,
        "source_text": source_text,
        "target_field": target_field,
        "target_text": target_text,
        "target_missing": bool(target_missing),
        "locked_terms": [
            {"source": term["source"], "target": term["target"]}
            for term in locked_terms
        ],
        "extra_prompt": extra_prompt or "",
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)


def build_sql_translation_system_prompt():
    return (
        "You are a professional translator and reviewer for SQL seed data.\n"
        "Return JSON only with keys: verdict, candidate_translation, reason.\n"
        "verdict must be either accurate or needs_update.\n"
        "candidate_translation must contain only the translated English field text, never return SQL.\n"
        "Preserve placeholders exactly, including {0}, {}, %s, ${name} and similar forms.\n"
        "If locked_terms are provided, candidate_translation must use the target terms exactly as given.\n"
        "If target_text is already accurate, set verdict=accurate and candidate_translation to the unchanged target_text."
    )


def _build_update_sql(item):
    return "UPDATE {table} SET {target_field} = '{value}' WHERE {primary_key_field} = {primary_key};".format(
        table=item.get("table_expression", ""),
        target_field=item.get("target_field_sql", ""),
        value=_escape_sql_string(item.get("candidate_text", "")),
        primary_key_field=item.get("primary_key_field_sql", ""),
        primary_key=item.get("primary_key_literal", ""),
    )


def _build_scan_event(path, line, reason):
    return {
        "at": _timestamp(),
        "label": "已跳过",
        "source_path": str(path),
        "line": int(line),
        "primary_key_value": "",
        "source_text": "",
        "target_text": reason,
    }


def _load_written_item_ids(path):
    text = Path(path).read_text(encoding="utf-8")
    written = set()
    for line in text.splitlines():
        if line.startswith("-- item:"):
            written.add(line[len("-- item:"):].strip())
    return written


def _mask_sql_comments(text):
    chars = []
    index = 0
    length = len(text)
    in_string = False
    in_line_comment = False
    in_block_comment = False
    while index < length:
        char = text[index]
        next_char = text[index + 1] if index + 1 < length else ""
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
                chars.append(char)
            else:
                chars.append(" ")
            index += 1
            continue
        if in_block_comment:
            if char == "*" and next_char == "/":
                chars.append(" ")
                chars.append(" ")
                index += 2
                in_block_comment = False
                continue
            if char == "\n":
                chars.append(char)
            else:
                chars.append(" ")
            index += 1
            continue
        if in_string:
            chars.append(char)
            if char == "'" and next_char == "'":
                chars.append(next_char)
                index += 2
                continue
            if char == "'":
                in_string = False
            index += 1
            continue
        if char == "'" and not in_string:
            in_string = True
            chars.append(char)
            index += 1
            continue
        if char == "-" and next_char == "-":
            in_line_comment = True
            chars.append(" ")
            chars.append(" ")
            index += 2
            continue
        if char == "#":
            in_line_comment = True
            chars.append(" ")
            index += 1
            continue
        if char == "/" and next_char == "*":
            in_block_comment = True
            chars.append(" ")
            chars.append(" ")
            index += 2
            continue
        chars.append(char)
        index += 1
    return "".join(chars)


def _split_sql_statements(text, masked_text):
    statements = []
    start_index = None
    start_line = 1
    line = 1
    in_string = False
    index = 0
    length = len(masked_text)
    while index < length:
        char = masked_text[index]
        next_char = masked_text[index + 1] if index + 1 < length else ""
        if start_index is None and not char.isspace():
            start_index = index
            start_line = line
        if in_string:
            if char == "'" and next_char == "'":
                index += 2
                continue
            if char == "'":
                in_string = False
        else:
            if char == "'":
                in_string = True
            elif char == ";":
                if start_index is not None:
                    statements.append(
                        {
                            "text": text[start_index:index],
                            "masked_text": masked_text[start_index:index],
                            "line": start_line,
                        }
                    )
                    start_index = None
        if char == "\n":
            line += 1
        index += 1
    if start_index is not None:
        statements.append(
            {
                "text": text[start_index:],
                "masked_text": masked_text[start_index:],
                "line": start_line,
            }
        )
    return statements


def _parse_identifier_list(columns_text):
    inner = str(columns_text or "").strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]
    parts = _split_simple_csv(inner)
    result = []
    for part in parts:
        raw = part.strip()
        if not raw:
            continue
        result.append(
            {
                "raw": raw,
                "normalized": _normalize_identifier(raw),
            }
        )
    return result


def _parse_values_groups(values_text, base_line):
    groups = []
    in_string = False
    depth = 0
    start = None
    line = base_line
    group_line = base_line
    index = 0
    length = len(values_text)
    while index < length:
        char = values_text[index]
        next_char = values_text[index + 1] if index + 1 < length else ""
        if in_string:
            if char == "'" and next_char == "'":
                index += 2
                continue
            if char == "'":
                in_string = False
        else:
            if char == "'":
                in_string = True
            elif char == "(":
                if depth == 0:
                    start = index
                    group_line = line
                depth += 1
            elif char == ")":
                if depth > 0:
                    depth -= 1
                    if depth == 0 and start is not None:
                        groups.append(
                            {
                                "text": values_text[start:index + 1],
                                "line": group_line,
                            }
                        )
                        start = None
        if char == "\n":
            line += 1
        index += 1
    return groups


def _split_tuple_values(group_text):
    inner = str(group_text or "").strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]
    return _split_sql_csv(inner)


def _split_simple_csv(text):
    parts = []
    token = []
    in_backtick = False
    for char in text:
        if char == "`":
            in_backtick = not in_backtick
            token.append(char)
            continue
        if char == "," and not in_backtick:
            parts.append("".join(token))
            token = []
            continue
        token.append(char)
    parts.append("".join(token))
    return parts


def _split_sql_csv(text):
    parts = []
    token = []
    in_string = False
    depth = 0
    index = 0
    length = len(text)
    while index < length:
        char = text[index]
        next_char = text[index + 1] if index + 1 < length else ""
        if in_string:
            token.append(char)
            if char == "'" and next_char == "'":
                token.append(next_char)
                index += 2
                continue
            if char == "'":
                in_string = False
            index += 1
            continue
        if char == "'":
            in_string = True
            token.append(char)
            index += 1
            continue
        if char == "(":
            depth += 1
            token.append(char)
            index += 1
            continue
        if char == ")":
            if depth > 0:
                depth -= 1
            token.append(char)
            index += 1
            continue
        if char == "," and depth == 0:
            parts.append("".join(token))
            token = []
            index += 1
            continue
        token.append(char)
        index += 1
    parts.append("".join(token))
    return parts


def _normalize_identifier(value):
    text = str(value or "").strip()
    if text.startswith("`") and text.endswith("`"):
        text = text[1:-1]
    return text.replace("`", "").replace(" ", "").lower()


def _table_leaf_name(table_expression):
    text = str(table_expression or "").strip()
    if "." not in text:
        return text
    return text.split(".")[-1]


def _sql_value_to_text(token):
    value = str(token or "").strip()
    if not value:
        return ""
    if value.upper() == "NULL":
        return ""
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def _sql_value_to_display(token):
    value = str(token or "").strip()
    if not value:
        return ""
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def _escape_sql_string(value):
    return str(value or "").replace("'", "''")


def _safe_file_name_component(value):
    chars = []
    for char in str(value or ""):
        if char.isalnum() or char in ("-", "_"):
            chars.append(char)
        else:
            chars.append("_")
    result = "".join(chars).strip("_")
    return result or "table"


def _contains_locked_terms(candidate, locked_terms):
    value = str(candidate or "")
    for term in locked_terms:
        if term["target"] not in value:
            return False
    return True


def _timestamp():
    return datetime.now().astimezone().replace(microsecond=0).isoformat()
